// Devotional content for Stand. Shared by the app (as globals) and by
// scripts/build-day-pages.js (as a Node module).
const themes = [
  ["Stand","Ephesians 6:10–13","Be strong in the Lord and in his mighty power.","The first command of spiritual combat is not attack. It is to stand. Standing means refusing to let fear, anger, pressure, accusation, or uncertainty dictate who you become.","Father, establish me within before I attempt to change anything around me. Where I am frightened, give me courage. Where I am confused, give me clarity. Where I am angry, give me discipline. Where I am exhausted, renew my strength. I will not surrender my character to my circumstances. Help me stand.","I will stand in truth, walk in peace, and keep my character.","When something triggers you, pause and ask: What would standing in truth look like right now?"],
  ["Truth","Ephesians 6:14","Stand firm then, with the belt of truth buckled around your waist.","Truth is the first piece of armor. Spiritual combat begins with intellectual honesty: separating what you know, what you believe, what you assume, and what you fear.","God of truth, remove deception from around me and self-deception from within me. Do not merely show me the truths I want to discover. Show me truth itself. Give me courage to change my mind when evidence requires it. Let truth matter more than winning.","Truth matters more than my need to be right.","Divide one difficult situation into three columns: known, believed, and unknown."],
  ["Righteousness","Ephesians 6:14","Stand firm, with the breastplate of righteousness in place.","Spiritual warfare is not only about identifying wrongdoing in others. It asks whether your own conduct matches the standard you expect from everyone else.","Lord, search my motives. Expose hypocrisy, correct pride, remove vengeance, and strengthen integrity. Let my private character match my public words. May the right thing remain right even when nobody sees it.","My character is measured by what I practice, not what I proclaim.","Do one right thing today when nobody is watching."],
  ["Peace","Ephesians 6:15","Have your feet fitted with the readiness that comes from the gospel of peace.","Peace is not passivity. It can require boundaries, hard conversations, repair, or walking away. Peace refuses unnecessary chaos without hiding from necessary truth.","Prince of Peace, make me an instrument of peace without making me afraid of necessary conflict. Help me know when to speak, when to listen, when to act, and when to walk away.","I can carry peace into a place without surrendering truth.","Remove one unnecessary source of conflict from your day."],
  ["Faith","Ephesians 6:16","Take up the shield of faith, with which you can extinguish all the flaming arrows.","Faith does not pretend difficulty is unreal. Faith refuses to give difficulty ultimate authority. It makes room for a next faithful step before the whole path is visible.","God, there are outcomes I cannot control, questions I cannot answer, and people I cannot change. I place them before You. Give me enough faith to take the next faithful step.","This difficulty is real, but it does not control my character.","Name one uncontrollable outcome and release it aloud."],
  ["Guard the Mind","Ephesians 6:17","Take the helmet of salvation.","Rumination can turn one painful moment into hundreds of imagined ones. Guarding the mind means deciding which thoughts deserve continued attention.","God, protect my mind. Interrupt obsessive fear, challenge catastrophic thinking, and expose false narratives. Return me to what is true, useful, honorable, and within my responsibility.","My mind does not need to solve everything today.","Test one recurring thought: Is it true, known, useful, and actionable?"],
  ["The Word","Ephesians 6:17","Take the sword of the Spirit, which is the word of God.","Words shape interpretation, and interpretation shapes action. Sacred words can return you to courage when noise pulls you toward panic.","Lord, place words of truth within me before the world fills me with noise. Let Scripture challenge fear, pride, hatred, despair, and temptation.","Truth will remain after today's noise disappears.","Choose one short verse and return to it three times today."],
  ["Fear","Psalm 27:1","The Lord is my light and my salvation—whom shall I fear?","Fear predicts futures that have not happened. Courage returns to the responsibility directly in front of you.","Lord, bring me back to today. Give me courage for today's responsibility rather than anxiety about tomorrow's possibilities. I will prepare wisely, but I will not worship fear.","Fear may speak, but it does not get the final word.","Do one thing fear has persuaded you to postpone."],
  ["Anger","James 1:19–20","Be quick to listen, slow to speak and slow to become angry.","Anger can carry information about a wound, boundary, injustice, or fear. It becomes dangerous when it moves from messenger to master.","God, let anger become information rather than my master. Show me what lies beneath it, then teach me to respond with clarity and proportion.","I can feel anger without surrendering my conduct to it.","Delay an angry response until your body becomes calm."],
  ["Resentment","Romans 12:21","Do not be overcome by evil, but overcome evil with good.","Resentment keeps another person's wrongdoing active inside you. Releasing it does not excuse harm; it refuses to let harm reproduce itself.","Lord, I refuse to carry another person's wrongdoing inside me indefinitely. Help me pursue accountability without revenge. Let evil stop with me.","What harmed me will not determine what I become.","Name one resentment you are ready to begin releasing."],
  ["Pride","Proverbs 16:18","Pride goes before destruction, a haughty spirit before a fall.","Pride turns uncertainty into performance and correction into threat. Humility creates freedom to learn, repair, and receive help.","God, protect me from needing to win every argument. Give me freedom to say: I was wrong. I do not know. I need help. Please forgive me.","I do not lose dignity when I become teachable.","Admit one thing you do not know."],
  ["Temptation","Matthew 4:10","Worship the Lord your God, and serve him only.","Temptation often becomes powerful through rationalization. Freedom grows when you notice the decision point before it becomes a habit.","Lord, help me recognize temptation before I rename or excuse it. Give me strength during the few moments when a decision becomes a pattern.","I can choose what strengthens the person I am becoming.","Remove one environmental trigger connected to a recurring temptation."],
  ["Despair","Psalm 42:11","Put your hope in God, for I will yet praise him.","Feelings are powerful witnesses, but imperfect prophets. Despair speaks in absolutes; hope looks for the next constructive step.","God, when my feelings tell me nothing will improve, remind me that this moment is not the whole story. Give me enough hope for one more faithful step.","I do not need all the hope—only enough for the next step.","Do one constructive thing for your future self."],
  ["Rest","Matthew 11:28","Come to me, all you who are weary and burdened, and I will give you rest.","Exhaustion is not proof of faithfulness. Rest restores perspective, restraint, attention, and the ability to love well.","Lord, I surrender the belief that exhaustion proves devotion. Teach me to rest without guilt. Restore my body, quiet my mind, and renew my spirit.","Rest is part of faithfulness, not a departure from it.","Protect a period of genuine rest today."],
  ["Guard Your Words","James 3:5","The tongue is a small part of the body, but it makes great boasts.","Words can clarify or inflame, defend dignity or destroy it. Spiritual discipline places a guard between emotional impulse and lasting speech.","God, put a guard over my mouth. Let my words be truthful without cruelty, strong without abuse, and clear without manipulation.","My words will serve truth, repair, and necessary boundaries.","Read an emotional message twice before sending it."],
  ["Discernment","James 1:5","If any of you lacks wisdom, you should ask God.","Discernment separates observable behavior from stories about motives. It holds alertness and humility together.","Lord, give me discernment without suspicion, alertness without paranoia, confidence without arrogance, and compassion without gullibility.","I can observe carefully without pretending to know every motive.","Write the facts of one situation separately from your interpretation."],
  ["Boundaries","Proverbs 4:23","Above all else, guard your heart, for everything you do flows from it.","Forgiveness does not require unlimited access. A healthy boundary protects peace and responsibility; punishment tries to control another person's pain.","God, teach me to establish boundaries without hatred. Remove bitterness without removing discernment. Let forgiveness free my heart while wisdom guards the door.","I can love someone without granting unsafe access.","Name one boundary that protects peace without punishing."],
  ["False Accusations","Psalm 37:6","He will make your righteous reward shine like the dawn.","You can answer falsehood with calm facts without making every opinion your assignment. Document what matters; release what you cannot control.","Lord, when misunderstood, keep me from destroying my peace trying to control every perception. Help me speak truth, correct what is false, accept what is mine, and release the rest.","An accusation does not define my identity.","Replace repeated self-defense with one clear factual statement."],
  ["Forgiveness","Colossians 3:13","Forgive as the Lord forgave you.","Forgiveness can be a process. It releases the desire for revenge; it does not erase memory, accountability, consequences, or wise distance.","God, begin the work of forgiveness within me. Remove my desire to see another suffer merely because I suffered. Keep wisdom and boundaries intact.","I release vengeance while preserving truth and responsibility.","Pray for freedom from resentment, not forced reconciliation."],
  ["Love Your Enemy","Matthew 5:44","Love your enemies and pray for those who persecute you.","Loving an enemy does not mean calling harm good. It means refusing dehumanization while seeking protection, truth, and accountability.","Lord, teach me to oppose harmful behavior without dehumanizing the person responsible. Protect my heart from becoming what hurt me.","I can seek accountability without hatred.","Refuse dehumanizing language about someone you oppose."],
  ["Protect the Vulnerable","Isaiah 1:17","Seek justice. Defend the oppressed.","Strength becomes holy when it protects rather than dominates. Advocacy serves another person's dignity instead of using their pain for recognition.","God, make my strength useful to someone vulnerable. Give me courage to protect without controlling, advocate without exploiting, and serve without needing recognition.","My strength is entrusted to me for service.","Help someone who cannot repay you."],
  ["Courage","Joshua 1:9","Be strong and courageous. Do not be afraid.","Courage is not the absence of fear. It is faithful movement while fear is present.","God, give me enough courage to move while fear is present. Keep me from waiting for perfect confidence before doing what is right.","I can be afraid and still be faithful.","Take one action you have been avoiding."],
  ["Wisdom","Proverbs 3:5–6","Trust in the Lord with all your heart and lean not on your own understanding.","Urgency can impersonate wisdom. Wise decisions create room for counsel, consequences, conscience, and time.","Lord, slow me down enough to see clearly. Keep urgency from making choices that wisdom would refuse.","I am permitted to pause before a non-emergency decision.","Delay one decision long enough to consider its consequences."],
  ["Justice","Micah 6:8","Act justly and love mercy and walk humbly with your God.","Justice is not favoritism for our own side. It applies the same dignity, evidence, and standard even to people we dislike.","God, give me a love for justice that includes justice for people I oppose. Protect me from demanding standards for others that I reject for myself.","Truth and fairness do not change sides to favor me.","Apply to yourself the standard you apply to another."],
  ["Mercy","Luke 6:36","Be merciful, just as your Father is merciful.","Mercy makes room for human weakness and repair without erasing responsibility. It is neither denial nor enabling.","Lord, let mercy temper judgment without hiding truth. Teach me the difference between compassion and enabling.","I can make room for repair while keeping healthy limits.","Give someone room to correct a genuine mistake."],
  ["Humility","Philippians 2:3","In humility value others above yourselves.","Humility is accurate self-knowledge: neither self-exaltation nor self-erasure. It listens for truth even when correction feels uncomfortable.","God, make me teachable. When correction comes, help me examine it before rejecting it. Keep me secure enough to learn.","Correction can refine me without defining me.","Ask someone trustworthy: What am I not seeing?"],
  ["Perseverance","Romans 5:4","Perseverance produces character; and character, hope.","Some battles are won through endurance rather than dramatic victory. Small faithful acts compound when visible results are slow.","Lord, give me strength to continue doing what is right when results are delayed. Protect me from confusing slow progress with failure.","Faithfulness still counts when nobody applauds it.","Complete one small task connected to a long-term goal."],
  ["Surrender","Matthew 6:34","Do not worry about tomorrow, for tomorrow will worry about itself.","Surrender releases outcomes while retaining responsibility. It is not giving up; it is returning each burden to its proper owner.","Father, I surrender outcomes while retaining responsibility. I will do what belongs to me and release what does not.","I am responsible for faithfulness, not control of every outcome.","Write what you cannot control and physically put the paper away."],
  ["Become the Light","Matthew 5:14","You are the light of the world.","Healing becomes service when your presence offers courage, truth, stability, compassion, and hope to someone else.","God, do more than deliver me from darkness. Teach me to carry light. Make my presence a source of courage, truth, stability, compassion, and hope.","What I have survived can become light for someone else.","Encourage one person who is struggling."],
  ["Character","Ephesians 6:18","Pray in the Spirit on all occasions with all kinds of prayers and requests.","The deepest victory may not be defeating an enemy. It may be that hatred did not make you hateful, deception dishonest, fear cowardly, or suffering cruel.","Father, clothe me in truth, guard my heart, direct my feet toward peace, strengthen my faith, protect my mind, and place Your Word within me. When I have done everything I know how to do, teach me to stand.","Darkness around me will not become darkness within me.","Review the journey. Choose one practice to carry into the next thirty days."]
];

const weeks = [
  "WEEK ONE · ESTABLISH THE GROUND",
  "WEEK TWO · CONFRONT THE INNER BATTLE",
  "WEEK THREE · COMBAT IN RELATIONSHIPS",
  "WEEK FOUR · TRANSFORMATION",
  "DAY THIRTY · THE FINAL BATTLE IS CHARACTER"
];

// Focused short tracks. Each day follows the same shape as `themes`:
// [title, reference, verse, reflection, prayer, declaration, practice]
const tracks = {
  core: {
    id: "core",
    name: "Stand — 30 Days of Spiritual Combat",
    short: "The 30-Day Journey",
    days: themes,
    weeks
  },
  unknown: {
    id: "unknown",
    name: "Fear of the Unknown",
    short: "Fear of the Unknown",
    weeks: ["FEAR OF THE UNKNOWN · FIVE DAYS"],
    days: [
      ["The Unwritten Page","Proverbs 3:5–6","Trust in the Lord with all your heart and lean not on your own understanding.","Fear of the unknown writes confident endings to stories that have not begun. Trust does not demand the whole plot; it takes the next line with the Author.","Father, I keep trying to read pages that have not been written. Teach me to trust You with the chapters I cannot see, and give me faithfulness for the page in front of me.","I do not need to know the ending to trust the Author.","Write down one unknown you keep rehearsing, and beside it the one step that is actually yours today."],
      ["Daily Bread","Matthew 6:11","Give us today our daily bread.","Provision arrives daily, not in advance — which is exactly why the unknown feels underfunded. Grace for tomorrow will be issued tomorrow.","Lord, I confess I want a stockpile and You offer bread for today. Feed me for this day's needs, and quiet the hunger for guarantees You never promised.","Today has enough grace in it for today.","Name today's actual needs — not tomorrow's possible ones — and pray only for those."],
      ["Light for the Next Step","Psalm 119:105","Your word is a lamp for my feet, a light on my path.","A lamp for feet lights steps, not horizons. Scripture rarely shows the whole road, but it never fails the next stretch of ground.","God, when I strain to see the horizon, lower my eyes to the ground You have lit. Give me courage to take the step I can see instead of waiting for the map.","Enough light for one step is enough light.","Take the one clear step you have been postponing while waiting for certainty."],
      ["Held","Isaiah 41:10","Do not fear, for I am with you; do not be dismayed, for I am your God.","The promise for the unknown is not a preview; it is a presence. Whatever tomorrow holds, you will not hold it alone.","Father, You do not hand me the future — You hold my hand into it. When dread rises tonight or tomorrow, remind me that presence outweighs prediction.","I am not walking into the unknown alone.","Each time a what-if surfaces today, answer it aloud: 'And God will be there too.'"],
      ["Open Hands","Philippians 4:6–7","Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.","Anxiety grips; prayer opens the hand. What is presented to God can stop being carried alone, and peace stands guard where control used to pace.","Lord, here is everything I have been holding with a closed fist. I present it — named, specific, with thanks — and ask for the peace that guards what I cannot.","What I hand to God, I no longer carry alone.","Turn today's biggest what-if into one specific, thankful request — prayed once, not rehearsed all day."]
    ]
  },
  night: {
    id: "night",
    name: "Night Fear & Sleep",
    short: "Night Fear & Sleep",
    weeks: ["NIGHT FEAR & SLEEP · FIVE DAYS"],
    days: [
      ["Lying Down","Psalm 4:8","In peace I will lie down and sleep, for you alone, Lord, make me dwell in safety.","Sleep is an act of trust: for a few hours you stop managing the world, and it goes on being held. Lying down in peace is not denial — it is a handoff.","Father, as I lie down I resign as night watchman. What I did not finish today, You are not worried about. Let my body rest under Your safety, not my vigilance.","I can end this day; God does not end with it.","Choose a consistent handoff moment tonight — lights, prayer, done — and keep it."],
      ["The Watchman","Psalm 121:3–4","He who watches over you will not slumber; indeed, he who watches over Israel will neither slumber nor sleep.","Someone is up all night, and it does not have to be you. The watch is already staffed; your shift ends at bedtime.","Lord, You stay awake so I do not have to. Take the night shift — the replaying, the pre-living, the listening for trouble — and let me sleep like someone who is guarded.","The night watch is God's shift, not mine.","When you wake in the night, say once: 'You are awake, so I don't have to be' — then let the thought pass."],
      ["Thoughts at Midnight","Psalm 94:19","When anxiety was great within me, your consolation brought me joy.","Midnight thoughts lie about their size; at 3 a.m. every problem doubles. Consolation does not solve the problem — it right-sizes it until morning can.","God, my midnight mind exaggerates. Bring Your consolation into the loop of thoughts I cannot stop, and hold my questions until daylight, when they shrink to their true size.","Nothing is decided at 3 a.m.","Keep paper by the bed: write the worry down once, and let the page hold it until morning."],
      ["Darkness Is Not Dark","Psalm 139:11–12","Even the darkness will not be dark to you; the night will shine like the day.","Darkness changes what you can see, not what God can. The room at night is exactly as held as the room at noon.","Father, the dark makes everything feel unsupervised. Remind my body of what my faith knows: night is only dark from my side. Stay near until I stop checking.","The dark is not empty; it is watched.","Tonight, take one fear you would have whispered to the darkness and speak it to God instead."],
      ["New Mercies","Lamentations 3:22–23","His compassions never fail. They are new every morning.","However the night went — restless, wakeful, afraid — morning does not carry it forward. Mercy is not a rollover balance; it is reissued at sunrise.","God, thank You that hard nights do not tax new mornings. Whatever tonight brings, let me wake to mercies that keep no record of my worst hours.","Morning mercy is new — last night does not bill it.","On waking, before checking anything, name one mercy already true of this morning."]
    ]
  }
};

// Recorded narration files that exist under audio/. Keys for days are
// "<trackId>-<dayIndex>"; SOS entries are indexed by sosSets order.
// Add entries here as new recordings land — days without one fall back
// to the device's text-to-speech narration.
const recordedAudio = {
  days: {
    // "core-0": "audio/day-01.mp3"  — add entries as recordings land
  },
  sos: []
};

if (typeof module !== "undefined" && module.exports) module.exports = { themes, weeks, tracks, recordedAudio };
