// Spanish devotional content, parallel to content.js. Shared by the app (as a
// global) and by scripts (as a Node module).
//
// Each day is the same seven fields as its English counterpart:
//   [title, reference, verse, reflection, prayer, declaration, practice]
//
// Scripture is the Reina-Valera 1909, which is public domain. Every excerpt is
// a contiguous substring of that text -- `npm run verify:scripture` checks all
// 108 against scripts/es-source.json and fails the build if one is not.

const esGroups = {
  "THE 30-DAY JOURNEY": "EL CAMINO DE 30 DÍAS",
  "FEAR TRACKS": "CAMINOS PARA EL MIEDO",
  "COURAGE STORIES": "HISTORIAS DE VALOR"
};

const esTracks = {
  core: {
    name: "Firme — 30 días de combate espiritual",
    short: "El camino de 30 días",
    weeks: ["SEMANA UNO · ESTABLECER EL TERRENO","SEMANA DOS · ENFRENTAR LA BATALLA INTERIOR","SEMANA TRES · COMBATE EN LAS RELACIONES","SEMANA CUATRO · TRANSFORMACIÓN","DÍA TREINTA · LA BATALLA FINAL ES EL CARÁCTER"],
    days: [
      ["Firmeza","Efesios 6:10–13","Confortaos en el Señor, y en la potencia de su fortaleza.","El primer mandato del combate espiritual no es atacar. Es mantenerse firme. Estar firme significa negarte a que el miedo, la ira, la presión, la acusación o la incertidumbre decidan en quién te conviertes.","Padre, afírmame por dentro antes de que intente cambiar lo que me rodea. Donde tengo miedo, dame valor. Donde estoy confundido, dame claridad. Donde estoy airado, dame dominio propio. Donde estoy agotado, renueva mis fuerzas. No entregaré mi carácter a mis circunstancias. Ayúdame a estar firme.","Estaré firme en la verdad, caminaré en paz y guardaré mi carácter.","Cuando algo te altere, detente y pregunta: ¿cómo sería estar firme en la verdad ahora mismo?"],
      ["Verdad","Efesios 6:14","Estad pues firmes, ceñidos vuestros lomos de verdad.","La verdad es la primera pieza de la armadura. El combate espiritual comienza con honestidad intelectual: separar lo que sabes, lo que crees, lo que supones y lo que temes.","Dios de verdad, quita el engaño de mi alrededor y el autoengaño de mi interior. No me muestres solamente las verdades que quiero encontrar. Muéstrame la verdad misma. Dame valor para cambiar de opinión cuando la evidencia lo exija. Que la verdad me importe más que ganar.","La verdad importa más que mi necesidad de tener razón.","Divide una situación difícil en tres columnas: lo que sabes, lo que crees y lo que ignoras."],
      ["Justicia","Efesios 6:14","Vestidos de la cota de justicia.","La guerra espiritual no consiste solo en señalar el mal en los demás. Pregunta si tu propia conducta corresponde al criterio que esperas de todos los demás.","Señor, examina mis motivos. Expón la hipocresía, corrige el orgullo, quita la venganza y fortalece la integridad. Que mi carácter en privado corresponda a mis palabras en público. Que lo correcto siga siendo correcto aunque nadie lo vea.","Mi carácter se mide por lo que practico, no por lo que proclamo.","Haz hoy una cosa correcta cuando nadie te esté mirando."],
      ["Paz","Efesios 6:15","Y calzados los pies con el apresto del evangelio de paz.","La paz no es pasividad. Puede exigir límites, conversaciones difíciles, reparación o retirarse. La paz rechaza el caos innecesario sin esconderse de la verdad necesaria.","Príncipe de Paz, hazme instrumento de paz sin hacerme temeroso del conflicto necesario. Ayúdame a saber cuándo hablar, cuándo escuchar, cuándo actuar y cuándo retirarme.","Puedo llevar paz a un lugar sin entregar la verdad.","Quita de tu día una fuente de conflicto que no sea necesaria."],
      ["Fe","Efesios 6:16","Sobre todo, tomando el escudo de la fe, con que podáis apagar todos los dardos de fuego del maligno.","La fe no finge que la dificultad no es real. La fe se niega a darle autoridad definitiva. Abre espacio para un siguiente paso fiel antes de que se vea el camino entero.","Dios, hay resultados que no puedo controlar, preguntas que no puedo responder y personas que no puedo cambiar. Los pongo delante de Ti. Dame fe suficiente para dar el siguiente paso fiel.","Esta dificultad es real, pero no gobierna mi carácter.","Nombra un resultado que no puedes controlar y suéltalo en voz alta."],
      ["Guarda la mente","Efesios 6:17","Y tomad el yelmo de salud.","La rumiación puede convertir un momento doloroso en cientos de momentos imaginados. Guardar la mente es decidir cuáles pensamientos merecen seguir recibiendo tu atención.","Dios, protege mi mente. Interrumpe el miedo obsesivo, confronta el pensamiento catastrófico y expón las narrativas falsas. Devuélveme a lo que es verdadero, útil, honroso y propio de mi responsabilidad.","Mi mente no tiene que resolverlo todo hoy.","Examina un pensamiento recurrente: ¿es cierto, comprobado, útil y accionable?"],
      ["La Palabra","Efesios 6:17","La espada del Espíritu; que es la palabra de Dios.","Las palabras dan forma a la interpretación, y la interpretación da forma a la acción. Las palabras sagradas pueden devolverte al valor cuando el ruido te empuja al pánico.","Señor, pon palabras de verdad dentro de mí antes de que el mundo me llene de ruido. Que la Escritura confronte el miedo, el orgullo, el odio, la desesperación y la tentación.","La verdad permanecerá cuando el ruido de hoy desaparezca.","Escoge un versículo breve y vuelve a él tres veces hoy."],
      ["Miedo","Salmo 27:1","Jehová es mi luz y mi salvación: ¿de quién temeré?","El miedo predice futuros que no han ocurrido. El valor regresa a la responsabilidad que tienes justo delante.","Señor, tráeme de vuelta al día de hoy. Dame valor para la responsabilidad de hoy en lugar de ansiedad por las posibilidades de mañana. Me prepararé con prudencia, pero no adoraré al miedo.","El miedo puede hablar, pero no tiene la última palabra.","Haz una cosa que el miedo te ha convencido de posponer."],
      ["Ira","Santiago 1:19–20","Todo hombre sea pronto para oir, tardío para hablar, tardío para airarse.","La ira puede traer información sobre una herida, un límite, una injusticia o un temor. Se vuelve peligrosa cuando pasa de mensajera a dueña.","Dios, que la ira sea información y no mi dueña. Muéstrame qué hay debajo de ella y enséñame luego a responder con claridad y proporción.","Puedo sentir ira sin entregarle mi conducta.","Aplaza una respuesta airada hasta que tu cuerpo se calme."],
      ["Resentimiento","Romanos 12:21","No seas vencido de lo malo; mas vence con el bien el mal.","El resentimiento mantiene activo dentro de ti el mal que otro hizo. Soltarlo no excusa el daño; se niega a que el daño se reproduzca.","Señor, me niego a llevar indefinidamente dentro de mí el mal que otro hizo. Ayúdame a buscar responsabilidad sin venganza. Que el mal se detenga en mí.","Lo que me hirió no determinará en qué me convierto.","Nombra un resentimiento que estés listo para empezar a soltar."],
      ["Orgullo","Proverbios 16:18","Antes del quebrantamiento es la soberbia; y antes de la caída la altivez de espíritu.","El orgullo convierte la incertidumbre en actuación y la corrección en amenaza. La humildad da libertad para aprender, reparar y recibir ayuda.","Dios, líbrame de necesitar ganar toda discusión. Dame libertad para decir: me equivoqué, no sé, necesito ayuda, perdóname.","No pierdo dignidad cuando me vuelvo enseñable.","Admite una cosa que no sabes."],
      ["Tentación","Mateo 4:10","Al Señor tu Dios adorarás y á él solo servirás.","La tentación suele volverse poderosa por la racionalización. La libertad crece cuando notas el punto de decisión antes de que se vuelva costumbre.","Señor, ayúdame a reconocer la tentación antes de renombrarla o excusarla. Dame fuerza en esos pocos instantes en que una decisión se convierte en patrón.","Puedo elegir lo que fortalece a la persona en que me estoy convirtiendo.","Quita un detonante de tu entorno ligado a una tentación recurrente."],
      ["Desesperanza","Salmo 42:11","Espera á Dios; porque aun le tengo de alabar.","Los sentimientos son testigos poderosos, pero profetas imperfectos. La desesperanza habla en absolutos; la esperanza busca el siguiente paso constructivo.","Dios, cuando mis sentimientos me digan que nada mejorará, recuérdame que este momento no es la historia completa. Dame esperanza suficiente para un paso fiel más.","No necesito toda la esperanza, solo la suficiente para el siguiente paso.","Haz una cosa constructiva por tu yo futuro."],
      ["Descanso","Mateo 11:28","Venid á mí todos los que estáis trabajados y cargados, que yo os haré descansar.","El agotamiento no es prueba de fidelidad. El descanso restaura la perspectiva, la mesura, la atención y la capacidad de amar bien.","Señor, entrego la idea de que el agotamiento prueba devoción. Enséñame a descansar sin culpa. Restaura mi cuerpo, aquieta mi mente y renueva mi espíritu.","El descanso es parte de la fidelidad, no una interrupción de ella.","Protege hoy un tiempo de descanso verdadero."],
      ["Guarda tus palabras","Santiago 3:5","La lengua es un miembro pequeño, y se gloría de grandes cosas.","Las palabras pueden aclarar o incendiar, defender la dignidad o destruirla. La disciplina espiritual pone un guarda entre el impulso emocional y la palabra que queda.","Dios, pon guarda a mi boca. Que mis palabras sean veraces sin crueldad, firmes sin maltrato y claras sin manipulación.","Mis palabras servirán a la verdad, a la reparación y a los límites necesarios.","Lee dos veces un mensaje emocional antes de enviarlo."],
      ["Discernimiento","Santiago 1:5","Si alguno de vosotros tiene falta de sabiduría, demándela á Dios.","El discernimiento separa la conducta observable de las historias sobre los motivos. Sostiene juntas la atención y la humildad.","Señor, dame discernimiento sin sospecha, atención sin paranoia, confianza sin arrogancia y compasión sin ingenuidad.","Puedo observar con cuidado sin fingir que conozco todos los motivos.","Escribe los hechos de una situación aparte de tu interpretación."],
      ["Límites","Proverbios 4:23","Sobre toda cosa guardada guarda tu corazón; porque de él mana la vida.","El perdón no exige acceso ilimitado. Un límite sano protege la paz y la responsabilidad; el castigo intenta controlar el dolor del otro.","Dios, enséñame a poner límites sin odio. Quita la amargura sin quitar el discernimiento. Que el perdón libere mi corazón mientras la sabiduría cuida la puerta.","Puedo amar a alguien sin darle un acceso que no es seguro.","Nombra un límite que proteja la paz sin castigar."],
      ["Acusaciones falsas","Salmo 37:6","Y exhibirá tu justicia como la luz, y tus derechos como el medio día.","Puedes responder a la falsedad con hechos serenos sin convertir cada opinión en tarea tuya. Documenta lo que importa; suelta lo que no puedes controlar.","Señor, cuando se me malinterprete, guárdame de destruir mi paz intentando controlar cada percepción. Ayúdame a decir la verdad, corregir lo falso, aceptar lo que me corresponde y soltar el resto.","Una acusación no define mi identidad.","Sustituye la defensa repetida por una sola declaración clara de los hechos."],
      ["Perdón","Colosenses 3:13","De la manera que Cristo os perdonó, así también hacedlo vosotros.","El perdón puede ser un proceso. Suelta el deseo de venganza; no borra la memoria, la responsabilidad, las consecuencias ni la distancia prudente.","Dios, comienza en mí la obra del perdón. Quita mi deseo de ver sufrir a otro solo porque yo sufrí. Deja intactas la sabiduría y los límites.","Suelto la venganza y conservo la verdad y la responsabilidad.","Ora por libertad del resentimiento, no por una reconciliación forzada."],
      ["Ama a tu enemigo","Mateo 5:44","Amad á vuestros enemigos, bendecid á los que os maldicen.","Amar a un enemigo no significa llamar bueno al daño. Significa negarse a deshumanizar mientras se busca protección, verdad y responsabilidad.","Señor, enséñame a oponerme a la conducta dañina sin deshumanizar a quien la comete. Protege mi corazón de volverse aquello que me hirió.","Puedo buscar responsabilidad sin odio.","Rechaza el lenguaje que deshumaniza a alguien a quien te opones."],
      ["Protege al vulnerable","Isaías 1:17","Aprended á hacer bien; buscad juicio, restituid al agraviado.","La fuerza se vuelve santa cuando protege en vez de dominar. La defensa del otro sirve a su dignidad en lugar de usar su dolor para obtener reconocimiento.","Dios, haz que mi fuerza le sirva a alguien vulnerable. Dame valor para proteger sin controlar, defender sin aprovecharme y servir sin necesitar reconocimiento.","Mi fuerza me fue confiada para servir.","Ayuda a alguien que no pueda devolverte el favor."],
      ["Valor","Josué 1:9","No temas ni desmayes, porque Jehová tu Dios será contigo en donde quiera que fueres.","El valor no es la ausencia de miedo. Es avanzar con fidelidad mientras el miedo está presente.","Dios, dame valor suficiente para avanzar mientras el miedo está presente. Guárdame de esperar una confianza perfecta antes de hacer lo correcto.","Puedo tener miedo y aun así ser fiel.","Da un paso que has estado evitando."],
      ["Sabiduría","Proverbios 3:5–6","Fíate de Jehová de todo tu corazón, y no estribes en tu prudencia.","La urgencia puede hacerse pasar por sabiduría. Las decisiones sabias dejan espacio al consejo, a las consecuencias, a la conciencia y al tiempo.","Señor, hazme ir más despacio para ver con claridad. Que la urgencia no tome decisiones que la sabiduría rechazaría.","Tengo permiso de detenerme antes de una decisión que no es urgente.","Aplaza una decisión lo suficiente para considerar sus consecuencias."],
      ["Justicia para todos","Miqueas 6:8","Solamente hacer juicio, y amar misericordia, y humillarte para andar con tu Dios.","La justicia no es favoritismo hacia los nuestros. Aplica la misma dignidad, la misma evidencia y el mismo criterio incluso a quienes nos desagradan.","Dios, dame un amor por la justicia que incluya la justicia para quienes me oponen. Guárdame de exigir a otros criterios que rechazo para mí mismo.","La verdad y la equidad no cambian de bando para favorecerme.","Aplícate a ti mismo el criterio que aplicas a otro."],
      ["Misericordia","Lucas 6:36","Sed pues misericordiosos, como también vuestro Padre es misericordioso.","La misericordia deja espacio a la debilidad humana y a la reparación sin borrar la responsabilidad. No es negación ni complicidad.","Señor, que la misericordia temple el juicio sin ocultar la verdad. Enséñame la diferencia entre la compasión y la complicidad.","Puedo dar espacio para reparar sin perder límites sanos.","Dale a alguien espacio para corregir un error genuino."],
      ["Humildad","Filipenses 2:3","En humildad, estimándoos inferiores los unos á los otros.","La humildad es conocerse con exactitud: ni exaltarse ni borrarse. Escucha la verdad aun cuando la corrección resulta incómoda.","Dios, hazme enseñable. Cuando llegue la corrección, ayúdame a examinarla antes de rechazarla. Dame seguridad suficiente para aprender.","La corrección puede refinarme sin definirme.","Pregúntale a alguien de confianza: ¿qué no estoy viendo?"],
      ["Perseverancia","Romanos 5:4","Y la paciencia, prueba; y la prueba, esperanza.","Algunas batallas se ganan por resistencia más que por una victoria dramática. Los pequeños actos fieles se acumulan cuando los resultados visibles tardan.","Señor, dame fuerza para seguir haciendo lo correcto cuando los resultados se demoran. Guárdame de confundir el avance lento con el fracaso.","La fidelidad cuenta aunque nadie la aplauda.","Completa una tarea pequeña ligada a una meta de largo plazo."],
      ["Entrega","Mateo 6:34","No os congojéis por el día de mañana; que el día de mañana traerá su fatiga.","La entrega suelta los resultados sin soltar la responsabilidad. No es rendirse; es devolver cada carga a quien le corresponde.","Padre, entrego los resultados y conservo mi responsabilidad. Haré lo que me toca y soltaré lo que no me toca.","Soy responsable de la fidelidad, no del control de cada resultado.","Escribe lo que no puedes controlar y guarda físicamente el papel."],
      ["Sé la luz","Mateo 5:14","Vosotros sois la luz del mundo.","La sanidad se vuelve servicio cuando tu presencia ofrece valor, verdad, estabilidad, compasión y esperanza a otra persona.","Dios, haz más que librarme de la oscuridad. Enséñame a llevar luz. Que mi presencia sea fuente de valor, verdad, estabilidad, compasión y esperanza.","Lo que he sobrevivido puede volverse luz para otro.","Anima a una persona que esté pasando por algo difícil."],
      ["Carácter","Efesios 6:18","Orando en todo tiempo con toda deprecación y súplica en el Espíritu.","La victoria más profunda quizá no sea derrotar a un enemigo. Quizá sea que el odio no te hizo odioso, ni el engaño deshonesto, ni el miedo cobarde, ni el sufrimiento cruel.","Padre, vísteme de verdad, guarda mi corazón, dirige mis pies hacia la paz, fortalece mi fe, protege mi mente y pon Tu Palabra dentro de mí. Cuando haya hecho todo lo que sé hacer, enséñame a estar firme.","La oscuridad a mi alrededor no se volverá oscuridad dentro de mí.","Repasa el camino recorrido. Escoge una práctica para llevar a los próximos treinta días."]
    ]
  },
  unknown: {
    name: "Miedo a lo desconocido",
    short: "Miedo a lo desconocido",
    weeks: ["MIEDO A LO DESCONOCIDO · CINCO DÍAS"],
    days: [
      ["La página en blanco","Proverbios 3:5–6","Fíate de Jehová de todo tu corazón, y no estribes en tu prudencia. Reconócelo en todos tus caminos, y él enderezará tus veredas.","El miedo a lo desconocido escribe finales seguros para historias que aún no empiezan. La confianza no exige la trama entera; toma el siguiente renglón junto al Autor.","Padre, sigo intentando leer páginas que todavía no se han escrito. Enséñame a confiarte los capítulos que no alcanzo a ver, y dame fidelidad para la página que tengo delante.","No necesito conocer el final para confiar en el Autor.","Escribe algo desconocido que repasas una y otra vez, y al lado el único paso que hoy sí te corresponde."],
      ["El pan de cada día","Mateo 6:11","Danos hoy nuestro pan cotidiano.","La provisión llega cada día, no por adelantado, y por eso lo desconocido se siente sin fondos. La gracia de mañana se entrega mañana.","Señor, confieso que quiero una reserva y Tú ofreces pan para hoy. Aliméntame para las necesidades de este día y aquieta el hambre de garantías que nunca prometiste.","El día de hoy tiene gracia suficiente para hoy.","Nombra tus necesidades reales de hoy, no las posibles de mañana, y ora solo por esas."],
      ["Luz para el siguiente paso","Salmo 119:105","Lámpara es á mis pies tu palabra, y lumbrera á mi camino.","Una lámpara a los pies alumbra pasos, no horizontes. La Escritura rara vez muestra el camino entero, pero nunca falla en el tramo siguiente.","Dios, cuando fuerce la vista buscando el horizonte, baja mis ojos al suelo que ya alumbraste. Dame valor para dar el paso que sí veo en vez de esperar el mapa.","Luz suficiente para un paso es luz suficiente.","Da ese paso claro que has ido posponiendo mientras esperas certeza."],
      ["Sostenido","Isaías 41:10","No temas, que yo soy contigo; no desmayes, que yo soy tu Dios que te esfuerzo.","La promesa para lo desconocido no es un adelanto; es una presencia. Sea lo que sea que traiga el mañana, no lo cargarás solo.","Padre, no me entregas el futuro: me tomas de la mano hacia él. Cuando el temor suba esta noche o mañana, recuérdame que la presencia pesa más que la predicción.","No camino solo hacia lo desconocido.","Cada vez que surja un «¿y si...?» hoy, respóndele en voz alta: «y Dios también estará allí»."],
      ["Manos abiertas","Filipenses 4:6–7","Por nada estéis afanosos; sino sean notorias vuestras peticiones delante de Dios en toda oración y ruego, con hacimiento de gracias.","La ansiedad aprieta; la oración abre la mano. Lo que se presenta a Dios deja de cargarse a solas, y la paz monta guardia donde antes daba vueltas el control.","Señor, aquí está todo lo que he venido sosteniendo con el puño cerrado. Lo presento, con nombre, concreto y con gratitud, y pido la paz que guarda lo que yo no puedo.","Lo que entrego a Dios ya no lo cargo solo.","Convierte tu mayor «¿y si...?» de hoy en una petición concreta y agradecida: orada una vez, no repasada todo el día."]
    ]
  },
  night: {
    name: "Miedo nocturno y sueño",
    short: "Miedo nocturno y sueño",
    weeks: ["MIEDO NOCTURNO Y SUEÑO · CINCO DÍAS"],
    days: [
      ["Al acostarte","Salmo 4:8","En paz me acostaré, y asimismo dormiré; porque solo tú, Jehová, me harás estar confiado.","Dormir es un acto de confianza: por unas horas dejas de administrar el mundo, y el mundo sigue sostenido. Acostarse en paz no es negación, es una entrega de turno.","Padre, al acostarme renuncio a ser el vigilante de la noche. Lo que no terminé hoy no Te quita el sueño. Que mi cuerpo descanse bajo Tu resguardo y no bajo mi vigilancia.","Puedo terminar este día; Dios no termina con él.","Escoge esta noche un momento fijo de entrega —luces, oración, listo— y respétalo."],
      ["El que vela","Salmo 121:3–4","Ni se dormirá el que te guarda. He aquí, no se adormecerá ni dormirá el que guarda á Israel.","Alguien pasa la noche despierto, y no tienes que ser tú. La guardia ya está cubierta; tu turno termina a la hora de dormir.","Señor, Tú permaneces despierto para que yo no tenga que estarlo. Toma el turno de la noche —lo que repaso, lo que anticipo, lo que escucho por si acaso— y déjame dormir como quien está guardado.","La guardia de la noche es el turno de Dios, no el mío.","Si despiertas de madrugada, di una sola vez: «Tú estás despierto, así que yo no tengo que estarlo», y deja pasar el pensamiento."],
      ["Pensamientos de medianoche","Salmo 94:19","En la multitud de mis pensamientos dentro de mí, tus consolaciones alegraban mi alma.","Los pensamientos de medianoche mienten sobre su tamaño; a las tres de la mañana todo problema se duplica. El consuelo no resuelve el problema: lo devuelve a su tamaño real hasta que la mañana pueda.","Dios, mi mente de medianoche exagera. Trae Tu consuelo al ciclo de pensamientos que no logro detener, y sostén mis preguntas hasta que amanezca y vuelvan a su tamaño verdadero.","Nada se decide a las tres de la mañana.","Deja papel junto a la cama: escribe la preocupación una vez y deja que la hoja la sostenga hasta la mañana."],
      ["La oscuridad no es oscura","Salmo 139:11–12","Aun las tinieblas no encubren de ti, y la noche resplandece como el día.","La oscuridad cambia lo que tú puedes ver, no lo que Dios ve. De noche, el cuarto está exactamente tan sostenido como a mediodía.","Padre, la oscuridad hace que todo parezca sin vigilancia. Recuérdale a mi cuerpo lo que mi fe ya sabe: la noche solo es oscura de mi lado. Quédate cerca hasta que deje de comprobar.","La oscuridad no está vacía; está vigilada.","Esta noche, toma un miedo que le habrías susurrado a la oscuridad y díselo a Dios."],
      ["Misericordias nuevas","Lamentaciones 3:22–23","Nunca decayeron sus misericordias. Nuevas son cada mañana; grande es tu fidelidad.","Como haya ido la noche —inquieta, en vela, con miedo—, la mañana no la arrastra. La misericordia no es un saldo acumulado: se emite de nuevo al amanecer.","Dios, gracias porque las noches difíciles no le cobran a las mañanas nuevas. Traiga lo que traiga esta noche, déjame despertar a misericordias que no llevan registro de mis peores horas.","La misericordia de la mañana es nueva; anoche no la factura.","Al despertar, antes de revisar nada, nombra una misericordia que ya sea cierta esta mañana."]
    ]
  },
  furnace: {
    name: "El horno — Daniel 3",
    short: "El horno",
    weeks: ["HISTORIA DE VALOR · EL HORNO · DANIEL 3"],
    days: [
      ["El decreto","Daniel 3:15","¿Y qué dios será aquel que os libre de mis manos?","A tres hombres se les da una decisión pública con un costo privado: inclinarse o arder. El miedo grita más fuerte donde la presión es legítima: autoridad real, consecuencia real, ninguna salida que deje todo intacto.","Dios, estoy delante de algo que de verdad puede costarme. Guárdame de fingir que el peligro es menor de lo que es, y guárdame de decidir quién soy en función de lo que amenaza.","La presión puede marcar mis circunstancias; no marca mi carácter.","Nombra exactamente aquello ante lo que te presionan a inclinarte, y escribe lo que te costaría negarte."],
      ["Y si no","Daniel 3:17–18","Y si no, sepas, oh rey, que tu dios no adoraremos, ni tampoco honraremos la estatua que has levantado.","Su valor no dependía de un rescate garantizado. «Y si no» es la frase que libera: la obediencia decidida antes de conocer el resultado ya no puede comprarse después con miedo.","Padre, quiero seguridad antes de comprometerme, y Tú pides compromiso antes de la seguridad. Dame una fe de «y si no»: una que se sostenga cuando la respuesta no sea la que pedí.","Haré lo correcto aunque el resultado no sea el que esperaba.","Termina esta frase en tus notas: «Aunque esto no salga como quiero, de todos modos ______»."],
      ["El cuarto varón","Daniel 3:25","He aquí que yo veo cuatro varones sueltos, que se pasean en medio del fuego, y ningún daño hay en ellos.","No fueron librados del fuego; fueron acompañados dentro de él. El rescate que casi todos piden es la salida. El rescate que casi todos reciben es la presencia, y es el más fuerte de los dos.","Señor, sigo pidiéndote que me saques. Si este es un fuego que piensas atravesar conmigo en vez de rodearlo, hazme consciente de Ti aquí dentro. Que note compañía donde esperaba solo calor.","Si tengo que atravesar esto, no lo atravesaré solo.","Mira atrás a una etapa dura que sobreviviste y escribe una manera concreta en que no estuviste solo."],
      ["Ni olor de fuego","Daniel 3:27","El fuego no se enseñoreó de sus cuerpos, ni cabello de sus cabezas fué quemado, ni sus ropas se mudaron, ni olor de fuego había pasado por ellos.","El detalle en que la historia se detiene no son las llamas, sino lo que quedó después: sin quemaduras, sin chamuscar, ni siquiera el olor. Lo que atraviesas no tiene por qué volverse lo que cargas.","Dios, no quiero salir de esto cargando su humo: amargado, quebradizo, desconfiado de todos. Haz la obra más honda: sácame de aquí sin que esto se me quede pegado.","Lo que atravieso no tiene por qué volverse lo que cargo.","Nombra una manera en que esta etapa dura ha empezado a cambiarte para mal, y un paso que empiece a deshacerlo."]
    ]
  },
  giant: {
    name: "El gigante — 1 Samuel 17",
    short: "El gigante",
    weeks: ["HISTORIA DE VALOR · EL GIGANTE · 1 SAMUEL 17"],
    days: [
      ["Cuarenta días de gritos","1 Samuel 17:16","Venía pues aquel Filisteo por la mañana y á la tarde, y presentóse por cuarenta días.","Un ejército quedó paralizado cuarenta días porque una amenaza siguió repitiéndose. El miedo rara vez necesita material nuevo; le basta la misma voz, mañana y tarde, hasta que todo el campamento se organiza en torno a ella.","Señor, algo me ha venido gritando cada mañana y cada tarde, y he acomodado mi vida alrededor de eso. Calla la repetición lo suficiente para que yo alcance a oír lo que de verdad es cierto.","Una amenaza repetida a diario sigue siendo una sola amenaza.","Escribe la frase que el miedo te repite. Cuenta cuántos días lleva diciéndola, y después escribe lo que realmente ha hecho."],
      ["Cinco piedras lisas","1 Samuel 17:40","Escogióse cinco piedras lisas del arroyo, y púsolas en el saco pastoril.","David rechazó una armadura que no le quedaba y tomó lo que ya había probado en el trabajo de todos los días. El valor rara vez se equipa con armas nuevas; se equipa con armas probadas.","Dios, guárdame de esperar un equipo que no tengo. Muéstrame lo que ya me has entrenado a hacer, y dame la humildad de usar cosas pequeñas y comprobadas.","Usaré lo que de verdad he practicado, no lo que se ve impresionante.","Enumera cinco cosas pequeñas y probadas que ya tienes —una habilidad, una persona, un hábito, un dato, un recurso— para lo que estás enfrentando."],
      ["No con espada ni lanza","1 Samuel 17:47","Jehová no salva con espada y lanza; porque de Jehová es la guerra.","El resultado no fue una medición de tamaño. Nombrar de quién es la batalla no te saca del campo; traslada el peso de tus hombros a los de Dios.","Padre, he venido cargando esto como si todo dependiera de mi fuerza. Es Tu batalla. Dame la parte que me toca y recupera la parte que nunca fue mía.","El resultado le pertenece a Dios; la fidelidad me pertenece a mí.","Traza una raya en una hoja: lo que hoy me toca a mí y lo que le toca a Dios. Después haz solo tu lado."],
      ["Corrió hacia el combate","1 Samuel 17:48","David se dió priesa, y corrió al combate contra el Filisteo.","El detalle que lo cambia todo es la dirección. Corrió hacia aquello de lo que todos los demás retrocedían, no porque el miedo faltara, sino porque demorar había dejado de ayudar.","Señor, he venido retrocediendo despacio ante algo que hay que enfrentar. Dame valor para acortar la distancia hoy, en vez de ensayarlo una semana más.","Enfrentarlo hoy cuesta menos que evitarlo otros cuarenta días.","Haz hoy esa única cosa evitada: haz la llamada, envía el mensaje, pide la cita, empieza la conversación."]
    ]
  },
  den: {
    name: "El foso — Daniel 6",
    short: "El foso",
    weeks: ["HISTORIA DE VALOR · EL FOSO · DANIEL 6"],
    days: [
      ["La trampa","Daniel 6:5","No hallaremos contra este Daniel ocasión alguna, si no la hallamos contra él en la ley de su Dios.","Sus acusadores no encontraron falta, así que fabricaron una regla que él tendría que quebrantar. Ser el blanco no prueba que hiciste mal, y hacer el bien no garantiza que te dejen en paz.","Dios, me están midiendo personas que buscan un motivo. Guárdame de vivir a la defensiva, de armar mis días alrededor de su búsqueda. Que mi conducta esté limpia y mi mente libre.","Ser acusado y ser culpable no son lo mismo.","Escribe el registro de los hechos de una situación —fechas, acciones, lo que en verdad se dijo— y luego deja de volver a discutirla en tu cabeza."],
      ["Las ventanas abiertas","Daniel 6:10","Hincábase de rodillas tres veces al día, y oraba, y confesaba delante de su Dios, como lo solía hacer antes.","Ni escaló ni se escondió. Siguió exactamente igual que antes. Bajo escrutinio, la fidelidad suele verse como la repetición nada llamativa de lo que ya hacías.","Señor, me tienta o exhibir mi integridad o esconderla. Déjame simplemente seguir: las mismas oraciones, los mismos criterios, el mismo cuidado, esté mirando alguien o no.","Seguiré haciendo lo correcto al mismo ritmo de siempre.","Mantén hoy una buena práctica común y corriente exactamente como la mantenías antes de que empezara la presión."],
      ["Bocas cerradas","Daniel 6:22","El Dios mío envió su ángel, el cual cerró la boca de los leones, para que no me hiciesen mal.","Algo que pretendía devorarlo fue simplemente mantenido cerrado. No todo peligro que abre la boca tiene permiso de cerrarla, y muchas veces solo lo sabrás desde dentro, después de la noche.","Padre, hay noches en que no puedo más que sentarme entre el peligro y esperar. Cierra lo que haya que cerrar. Donde no puedo protegerme, sé Tú la protección que no alcanzo a ver.","No todo lo que me amenaza tiene permiso de tocarme.","Esta noche, nombra un peligro que has venido imaginando en detalle y entrégalo en una sola frase en vez de ensayarlo."],
      ["Ninguna lesión","Daniel 6:23","Ninguna lesión se halló en él, porque creyó en su Dios.","El registro de aquella noche no fueron los rugidos; fue la ausencia de una herida. La vindicación vino de lo que era cierto, no de cuán alto se había defendido.","Dios, que hable el registro. Líbrame de la necesidad de ganar toda conversación sobre mi carácter, y deja que el tiempo y la verdad hagan el trabajo que yo sigo intentando hacer discutiendo.","No tengo que probar a gritos lo que el tiempo y la verdad mostrarán.","Sustituye hoy una explicación defensiva por una sola frase serena y factual, y déjala ahí."]
    ]
  },
  storm: {
    name: "La tormenta — Marcos 4",
    short: "La tormenta",
    weeks: ["HISTORIA DE VALOR · LA TORMENTA · MARCOS 4"],
    days: [
      ["Dormido en la popa","Marcos 4:38","¿Maestro, no tienes cuidado que perecemos?","La barca se llenaba y Jesús dormía. Su miedo no era solo el agua; era el silencio, la sensación de que nadie reaccionaba con la urgencia que el momento merecía.","Señor, he orado y nada parece moverse, y una parte de mí lo lee como indiferencia. Te digo la verdad de cómo se siente esto en lugar de fingir. No dejes que mi miedo sea la última palabra sobre Tu carácter.","El silencio no es lo mismo que la ausencia.","Dile a Dios en voz alta, una vez, esa frase honesta y sin editar que has venido suavizando."],
      ["Calla, enmudece","Marcos 4:39","Increpó al viento, y dijo á la mar: Calla, enmudece. Y cesó el viento, y fué hecha grande bonanza.","La calma no vino de que los discípulos achicaran agua más rápido. Tres palabras terminaron lo que todo su esfuerzo no pudo, y la autoridad de la tormenta resultó ser prestada.","Dios, he estado achicando agua: administrando, revisando, actualizando, arreglando. Habla quietud a la parte de esto que no puedo controlar, y a la parte de mí que no deja de trabajar en ello.","Lo más ruidoso de mi vida no es lo que manda en ella.","Toma noventa segundos: respira despacio y di «calla, enmudece» al exhalar. Usa el modo SOS si te ayuda."],
      ["¿Por qué estáis amedrentados?","Marcos 4:40","¿Por qué estáis así amedrentados? ¿Cómo no tenéis fe?","La pregunta llega después de la calma, no durante el pánico. No es un reproche por sentir miedo; es una invitación a examinar lo que el miedo les había convencido de creer.","Padre, cuando el agua se asiente, muéstrame qué me hizo creer el miedo: sobre Ti, sobre mí, sobre cómo termina esto. Corrígelo con ternura, y que la corrección se quede.","El miedo me dice cosas que jamás diría en voz alta; esas cosas no son ciertas.","Escribe una creencia que el miedo te vendió esta semana, y al lado lo que de verdad es cierto."],
      ["A la otra orilla","Marcos 4:35","Pasemos de la otra parte.","El destino del viaje se anunció antes de que empezara la tormenta. La tormenta cambió la travesía; nunca cambió la instrucción ni la orilla hacia la que iban.","Señor, recuérdame lo que dijiste antes de que todo esto empezara. Que la tormenta corrija mis plazos si hace falta, pero no mi dirección. Llévame a la otra orilla.","La tormenta puede cambiar mi travesía sin cambiar mi destino.","Nombra el compromiso que hiciste antes de esta etapa y da un paso pequeño que lo sostenga."]
    ]
  },
  unseen: {
    name: "El ejército invisible — 2 Reyes 6",
    short: "El ejército invisible",
    weeks: ["HISTORIA DE VALOR · EL EJÉRCITO INVISIBLE · 2 REYES 6"],
    days: [
      ["Rodeado al amanecer","2 Reyes 6:15","He aquí el ejército que tenía cercada la ciudad, con gente de á caballo y carros.","Se levantó, miró afuera y vio solamente la amenaza. Esa es una descripción honesta de muchas mañanas: lo primero que encuentran los ojos es lo que está formado en tu contra.","Dios, despierto ya contando lo que está en mi contra. Antes de sumar las amenazas de hoy, déjame hacer una cuenta exacta: de ayuda, de provisión, de lo que ya me ha sostenido.","Lo que veo primero en la mañana no es el inventario completo.","Antes de mirar el teléfono mañana, escribe tres cosas que sean ciertas y firmes en tu vida ahora mismo."],
      ["Más son los que están con nosotros","2 Reyes 6:16","No hayas miedo: porque más son los que están con nosotros que los que están con ellos.","Eliseo no argumentó que el ejército fuera pequeño. Dijo que la cuenta estaba incompleta. El miedo suele acertar sobre la amenaza y equivocarse en el total.","Señor, mi aritmética sigue dejándote fuera, y deja fuera a las personas que ya me diste. Corrige la cuenta. Déjame sentirme superado en número, pero en la dirección correcta.","El miedo cuenta bien la amenaza y no cuenta nada de la ayuda.","Enumera a todos y todo lo que de verdad está de tu lado ahora: personas, recursos, protecciones, evidencia pasada. Compáralo con la cuenta del miedo."],
      ["Abre sus ojos","2 Reyes 6:17","Ruégote, oh Jehová, que abras sus ojos para que vea.","La oración no fue por refuerzos sino por vista. Nada cambió fuera de la ciudad; lo que cambió fue lo que un hombre asustado alcanzó a ver de lo que ya estaba allí.","Padre, no Te pido que envíes lo que ya enviaste. Abre mis ojos. Muéstrame la ayuda que ha estado de pie a mi alrededor mientras yo contaba carros.","La ayuda que necesito quizá ya está aquí, sin que la vea.","Pregúntale a una persona de confianza qué ve en tu situación que quizá tú no estás viendo, y anota su respuesta."],
      ["Pan para el enemigo","2 Reyes 6:22","Pon delante de ellos pan y agua, para que coman y beban, y se vuelvan á sus señores.","La historia termina alimentando al ejército capturado en vez de destruirlo. El valor que se detiene en sobrevivir queda incompleto; el último compás de la fuerza verdadera es lo que se niega a hacerle a alguien que está a su merced.","Dios, cuando el miedo por fin se levante, guárdame de volverme aquello que me asustó. Dame la clase de valor que puede permitirse la misericordia y aun así mantener límites sabios.","La fuerza se prueba por lo que se niega a hacerle a quien no puede detenerla.","Escoge una persona sobre la que tengas algún poder pequeño y úsalo hoy para su bien y no para tu ventaja."]
    ]
  },
  throne: {
    name: "La sala del trono — Ester 4–5",
    short: "La sala del trono",
    weeks: ["HISTORIA DE VALOR · LA SALA DEL TRONO · ESTER 4–5"],
    days: [
      ["Para esta hora","Ester 4:14","¿Y quién sabe si para esta hora te han hecho llegar al reino?","Ester estaba a salvo, y esa seguridad era el problema: callar habría conservado su posición y costado la de todos los demás. Hay miedos que no son miedo al daño sino miedo a perder un lugar cómodo.","Dios, me he venido diciendo que el silencio es prudencia. Muéstrame con honestidad qué está protegiendo mi silencio, y dame valor para gastar algo de él por alguien que no puede hablar por sí mismo.","Callar también es una decisión, y también tiene un costo.","Nombra eso que estás en posición de decir y nadie más en la sala puede decir, y quién se beneficiaría si lo dijeras."],
      ["Si perezco, que perezca","Ester 4:16","Y así entraré al rey, aunque no sea conforme á la ley; y si perezco, que perezca.","No fue porque se sintiera lista ni porque esperara sobrevivir. La decisión se tomó antes de conocer la respuesta, que es el único lugar donde puede decidirse el valor.","Señor, sigo esperando sentirme lo bastante valiente. Déjame decidir esto mientras todavía tengo miedo, y luego sostenme firme lo suficiente para hacerlo de verdad.","Decidiré esto antes de saber cómo será recibido.","Escoge la conversación difícil y ponle fecha hoy: un día concreto, escrito."],
      ["El cetro de oro","Ester 5:2","El rey extendió á Esther el cetro de oro que tenía en la mano.","Había ensayado un peor escenario que no llegó. El miedo es un pronosticador seguro de sí mismo con un mal historial, y la única forma de auditarlo es comparar sus predicciones con lo que de verdad pasó.","Padre, he vivido cien veces la versión imaginada de esto. Dame la honestidad de notar cuántas veces la recepción temida nunca llegó.","El pronóstico del miedo no es un registro de resultados.","Escribe lo que predijiste antes de la última conversación difícil y después lo que realmente ocurrió. Guarda las dos cosas."],
      ["Primero el banquete","Ester 5:4","Si al rey place, venga hoy el rey con Amán al banquete que le he hecho.","Ya en la sala del trono, no lo soltó de golpe. Puso una mesa y esperó. El valor no es solo arrojo; también es momento oportuno, preparación y la paciencia de dejar que llegue la ocasión correcta.","Dios, dame la clase de valor que prepara. Guárdame de confundir la urgencia con la obediencia, y déjame hacer esto bien y no solamente rápido.","El valor que prepara sigue siendo valor.","Haz una cosa que ayude a que la conversación difícil aterrice mejor: los hechos en orden, el lugar elegido, la primera frase escrita."]
    ]
  },
  wall: {
    name: "El muro — Nehemías 4 y 6",
    short: "El muro",
    weeks: ["HISTORIA DE VALOR · EL MURO · NEHEMÍAS 4 Y 6"],
    days: [
      ["Se rieron de la obra","Nehemías 4:3","Aun lo que ellos edifican, si subiere una zorra derribará su muro de piedra.","Antes de que alguien atacara el muro, se burlaron de él. El desprecio dirigido a una obra sin terminar funciona porque el trabajo temprano siempre se ve frágil, y quien construye lo sabe mejor que los críticos.","Señor, alguien está haciendo que mi esfuerzo suene ridículo, y una parte de mí les da la razón. Sostenme construyendo durante la etapa en que la obra todavía no puede defenderse sola.","Sin terminar no es lo mismo que sin valor.","Escribe la frase burlona, y después escribe el siguiente ladrillo: la pieza más pequeña de la obra que puedes poner hoy."],
      ["La llana y la espada","Nehemías 4:17","Con la una mano trabajaban en la obra, y en la otra tenían la espada.","No dejaron de construir para atender la amenaza, ni fingieron que la amenaza fuera imaginaria. Las dos manos estaban ocupadas: una con la vigilancia, otra con la obra.","Dios, oscilo entre la negación y la defensa total. Enséñame a sostener ambas cosas: una guardia lúcida y una mano firme que sigue construyendo, sin soltar ninguna de las dos.","Puedo estar alerta y seguir construyendo al mismo tiempo.","Nombra la única precaución real que esta situación necesita. Tómala, vuelve a la obra y déjala ahí."],
      ["No puedo ir","Nehemías 6:3","Yo hago una grande obra, y no puedo ir.","Cuatro veces lo convocaron a una reunión y cuatro veces se negó a bajar. La invitación a discutir no es neutral; aceptarla es la manera en que la obra se detiene sin que nadie decida detenerla.","Padre, dame la disciplina de dejar algunas invitaciones sin responder. Guárdame de confundir una discusión larga con avance, y de bajar a una llanura donde no se construye nada.","No toda convocatoria merece que yo baje.","Identifica una discusión a la que te siguen invitando. Decline hoy: una vez, breve, sin un párrafo de justificación."],
      ["Cincuenta y dos días","Nehemías 6:15–16","Acabóse pues el muro el veinticinco del mes de Elul, en cincuenta y dos días.","No se terminó en un arranque. Se terminó en cincuenta y dos días corrientes de gente cargando piedras mientras les gritaban. Terminar suele ser simplemente haber durado más que la oposición.","Señor, déjame medir esto en días y no en sensaciones. Dame la resistencia de seguir poniendo piedra tras piedra hasta que la obra quede, sencilla y calladamente, hecha.","Esto se termina como se construye: un día corriente a la vez.","Cuenta los días que ya llevas trabajando en esto. Escribe el número donde lo veas mañana."]
    ]
  },
  water: {
    name: "El agua — Mateo 14",
    short: "El agua",
    weeks: ["HISTORIA DE VALOR · EL AGUA · MATEO 14"],
    days: [
      ["Un fantasma en la cuarta vigilia","Mateo 14:26","Viéndole andar sobre la mar, se turbaron, diciendo: Fantasma es. Y dieron voces de miedo.","La ayuda llegó y ellos gritaron. El miedo no solo teme las cosas malas; cuando lleva suficiente tiempo asustado, lee mal el rescate como una amenaza más.","Dios, llevo asustado el tiempo suficiente para desconfiar de las buenas noticias. Sosténme lo bastante para mirar dos veces lo que se acerca antes de decidir qué es.","No todo lo que me sobresalta está en mi contra.","Nombra algo a lo que reaccionaste con temor esta semana y comprueba si el temor estaba justificado."],
      ["Manda que yo vaya","Mateo 14:28–29","Señor, si tú eres, manda que yo vaya á ti sobre las aguas. Y él dijo: Ven.","Pedro pidió lo más difícil. La opción segura —quedarse en la barca con todos los demás— estuvo disponible todo el tiempo y nadie lo habría culpado por tomarla.","Señor, Te he estado pidiendo que calmes las cosas cuando una parte de mí está siendo invitada a salir. Si esto eres Tú, dilo, y dame el temple de pasar un pie por la borda.","La opción segura no siempre es la opción fiel.","Nombra lo que intentarías si supieras que te van a sostener. Da hoy su primer paso pequeño."],
      ["Comenzando a hundirse","Mateo 14:30","Mas viendo el viento fuerte, tuvo miedo; y comenzándose á hundir, dió voces, diciendo: Señor, sálvame.","El miedo llegó a la mitad del intento, no antes. Esta es la parte que más avergüenza: no no haberlo intentado nunca, sino haber flaqueado después de intentarlo.","Padre, tengo miedo en medio de algo que creí que me pediste, y me da vergüenza estar aquí. Déjame gritar con claridad en vez de callarme y hundirme.","Flaquear a la mitad no prueba que no debí empezar.","Di en voz alta la oración de tres palabras —Señor, sálvame— y luego dile a una persona que estás batallando."],
      ["Enseguida extendió la mano","Mateo 14:31","Y luego Jesús, extendiendo la mano, trabó de él.","No hubo sermón primero. Primero vino la mano, y la pregunta vino después, desde dentro del agarre. Ser sostenido es la parte de la historia que el miedo nunca predice.","Dios, gracias porque la mano no esperó a que yo recuperara la compostura. Cuando vuelva a hundirme, recuérdame qué tan rápido llegó la mano la última vez.","Cuando me hundí antes, no me dejaron allí.","Escribe una vez en que te fuiste a fondo y fuiste sostenido: por Dios, por una persona, por una provisión inesperada. Léelo la próxima vez que empieces a hundirte."]
    ]
  },
  basket: {
    name: "La arquilla — Éxodo 2",
    short: "La arquilla",
    weeks: ["HISTORIA DE VALOR · LA ARQUILLA · ÉXODO 2"],
    days: [
      ["Tres meses escondido","Éxodo 2:2","Viéndolo que era hermoso, túvole escondido tres meses.","Su primer instinto fue esconderlo, y durante tres meses funcionó. Casi todos los padres conocen ese tramo: el peligro es real, la protección es total y calladamente se está agotando.","Dios, he tenido a este hijo muy cerca y he mantenido lejos el peligro a pura fuerza. Estoy cansado, y me asusta el día en que mi cobertura no alcance. Quédate con nosotros en eso.","Puedo proteger con fiereza y aun así no poder proteger para siempre.","Nombra con honestidad de qué estás protegiendo hoy a tu hijo solo con esfuerzo, y quién más podría compartir ese peso."],
      ["Lo puso entre los juncos","Éxodo 2:3","Tomó una arquilla de juncos, y calafateóla con pez y betún, y colocó en ella al niño, y púsolo en un carrizal á la orilla del río.","No soltó sin más. Construyó la mejor arquilla que pudo, la selló, eligió el lugar, y entonces entregó lo que no podía controlar. La entrega es lo que ocurre después de la diligencia, no en lugar de ella.","Padre, déjame hacer todo lo que de verdad me toca por este hijo, y luego déjame poner la arquilla en el agua. Sostén Tú lo que mis manos no pueden.","Haré todo lo mío y soltaré lo que nunca fue mío.","Enumera lo que de verdad está en tu mano por tu hijo esta semana. Hazlo. Después nombra en voz alta la parte que entregas."],
      ["Su hermana se puso a lo lejos","Éxodo 2:4","Y paróse una hermana suya á lo lejos, para ver lo que le acontecería.","Alguien se quedó mirando. Ni tan cerca como para intervenir, ni tan lejos como para abandonar, que es la postura más difícil que un padre sostiene, y no es lo mismo que no hacer nada.","Señor, enséñame a estar presente sin retomar el control. Que mi mirada sea amor y no ansiedad, y dame la firmeza de permanecer a la distancia correcta.","Mirar desde lejos no es abandonar.","Escoge algo en lo que estabas a punto de intervenir. Quédate presente, quédate disponible, y deja que se desarrolle un poco más."],
      ["Críamelo","Éxodo 2:9","Lleva este niño, y críamelo, y yo te lo pagaré.","Lo que soltó volvió a sus propios brazos, y le pagaron por hacer abiertamente lo que había arriesgado la vida por hacer en secreto. No toda historia termina así, pero esta nombra la posibilidad que el miedo se niega a considerar.","Dios, mi miedo solo ha ensayado la versión que pierde. Déjame sostener la posibilidad de que lo que entrego pueda volver a mí transformado, y déjame vivir hoy sin decidir el final.","Lo que entrego no está automáticamente perdido.","Escribe el desenlace en que tu miedo insiste. Al lado, escribe otro desenlace igualmente posible."]
    ]
  },
  shiloh: {
    name: "Silo — 1 Samuel 1",
    short: "Silo",
    weeks: ["HISTORIA DE VALOR · SILO · 1 SAMUEL 1"],
    days: [
      ["Año tras año","1 Samuel 1:7","Por lo cual ella lloraba, y no comía.","Este es el miedo que tiene calendario: el mismo anhelo sin respuesta, llegando puntual, más hondo cada vuelta. La repetición hace que un dolor se sienta como un veredicto.","Dios, he traído esta misma petición durante años y ha empezado a sentirse como una puerta cerrada. Guárdame de convertir Tu silencio en una sentencia.","Una espera larga no es una respuesta definitiva.","Nombra lo que llevas más tiempo pidiendo. Dilo hoy una vez, sin añadir argumentos de por qué ya debería haber ocurrido."],
      ["Hablaba en su corazón","1 Samuel 1:13","Anna hablaba en su corazón, y solamente se movían sus labios, y su voz no se oía.","Oró con tanta honestidad que el sacerdote la creyó ebria. La oración verdadera muchas veces no es presentable, y ser malinterpretado mientras haces lo más sincero que has hecho en años es una herida aparte.","Señor, prefiero que la gente me lea mal mientras soy honesto contigo, antes que estar compuesto delante de ambos. Recibe esta oración en la forma en que salga.","Mi oración no tiene que ser presentable para ser oída.","Ora hoy una vez sin editar: en voz alta, sin pulir, incluyendo la parte que no dirías delante de nadie."],
      ["Su rostro ya no fue triste","1 Samuel 1:18","Y fuése la mujer su camino, y comió, y no estuvo más triste.","Todavía no había cambiado nada. La petición seguía pendiente, y aun así comió y su rostro se levantó. La paz llegó antes que la respuesta, que es la única clase de paz que puede llegar durante una espera larga.","Padre, he venido aplazando la paz hasta que la noticia sea buena. Dame algo de ella ahora, en la espera, antes de que nada se resuelva.","La paz puede llegar antes que la respuesta.","Haz una cosa buena y común que has venido aplazando hasta que esto se resuelva: una comida, una caminata, un plan con un amigo."],
      ["Prestado a Jehová","1 Samuel 1:28","Yo pues le vuelvo también á Jehová: todos los días que viviere, será de Jehová.","Lo que había suplicado, después lo sostuvo con las manos abiertas. La oración fue respondida y el agarre siguió suelto, que es más difícil que pedir y es todo lo que se les pide aprender a los padres.","Dios, cuando por fin reciba lo que he anhelado, guárdame de aferrarlo. Enséñame a sostener lo más precioso para mí como dije que lo haría cuando aún no lo tenía.","Lo que más amo lo sostengo con las manos abiertas.","Nombra una manera en que estás apretando el futuro de alguien. Suelta hoy un dedo: una decisión devuelta, un silencio guardado, una elección permitida."]
    ]
  },
  turning: {
    name: "Vuelto a la pared — Isaías 38",
    short: "Vuelto a la pared",
    weeks: ["HISTORIA DE VALOR · VUELTO A LA PARED · ISAÍAS 38"],
    days: [
      ["Ordena tu casa","Isaías 38:1","Ordena tu casa, porque tú morirás, y no vivirás.","Una frase de un médico puede reorganizar una vida en una tarde. A Ezequías se le dijo sin rodeos, y el decirlo no esperó a que él estuviera listo para oírlo.","Dios, me han dado una noticia que ya no puedo desoír, y mi mente no deja de correr. Hazme ir más despacio para enfrentar esta hora y no todas las horas que vienen después.","Solo tengo que enfrentar la parte de hoy.","Escribe lo que de verdad se te pide en los próximos siete días: citas, preguntas, una llamada. Nada más allá de eso."],
      ["Volvió su rostro a la pared","Isaías 38:2–3","Entonces volvió Ezechîas su rostro á la pared, é hizo oración á Jehová.","Se apartó de la sala para orar, y lloró mientras lo hacía. No hubo compostura ni actuación, y eso es lo que lo vuelve un modelo en lugar de una vergüenza.","Señor, he venido administrando mi cara para todos los que me rodean. Aquí, contigo, déjame parar. Toma el miedo y las lágrimas sin pedirme que primero las acomode.","No tengo que estar compuesto delante de Dios.","Toma diez minutos a solas y ora sin cuidar cómo suena. Las lágrimas son parte de la oración, no una interrupción."],
      ["He visto tus lágrimas","Isaías 38:5","Tu oración he oído, y visto tus lágrimas.","A Ezequías se le dio más tiempo. A muchas personas fieles no, y esta historia no es una fórmula que produzca años: la oración no sustituye al cuidado médico, y un desenlace no es una calificación de la fe de nadie. Lo primero en que el versículo insiste es en el oír y el ver, y esa parte está prometida a todos.","Padre, no fingiré saber qué harás con esto. Pido con sencillez sanidad y tiempo. Pase lo que pase, déjame estar seguro de que fui oído y de que mis lágrimas fueron vistas.","Sea como sea esto, mi oración fue oída y mis lágrimas fueron vistas.","Pide con claridad lo que quieres. Después cumple con una parte del cuidado práctico: la cita, el medicamento, la pregunta que has evitado hacerle a tu médico."],
      ["El que vive te alabará","Isaías 38:19","El que vive, el que vive, éste te confesará, como yo hoy.","Después lo escribió. Lo que aprendió en la peor semana de su vida se volvió un texto que otras personas asustadas podían leer, y eso es en lo que puede convertirse el sufrimiento cuando no se desperdicia.","Dios, no dejes que esta etapa pase por mí sin dejar algo aprovechable. Haz de lo que estoy aprendiendo aquí algo que sostenga a alguien después de mí.","Lo que estoy aprendiendo aquí no tiene que desperdiciarse.","Escribe una página sobre esta etapa para quien venga después: qué ayudó, qué no, qué te hubiera gustado que alguien te dijera."]
    ]
  },
  hem: {
    name: "El borde del manto — Marcos 5",
    short: "El borde del manto",
    weeks: ["HISTORIA DE VALOR · EL BORDE DEL MANTO · MARCOS 5"],
    days: [
      ["Doce años, y peor","Marcos 5:26","Había sufrido mucho de muchos médicos, y había gastado todo lo que tenía, y nada había aprovechado, antes le iba peor.","Doce años, todos los especialistas, todo el dinero, y la enfermedad seguía avanzando. La enfermedad crónica carga un segundo peso sobre el primero: el agotamiento de haberlo intentado ya todo.","Dios, estoy cansado de explicar esto, cansado de volver a intentarlo y cansado de esperar con cautela. Encuéntrame en el año doce, no solo al principio, cuando todavía tenía energía para esto.","Estar cansado de esperar no significa que haya fallado en la fe.","Nombra la parte de esto que es agotamiento y no enfermedad. Dile hoy esa cosa concreta a una persona."],
      ["Si tocare su vestido","Marcos 5:28","Si tocare tan solamente su vestido, seré salva.","No pidió que la presentaran. Vino por detrás, entre la multitud, apuntando al borde de un manto, porque cuando te han desestimado suficientes veces aprendes a alcanzar de maneras que no puedan negarte.","Señor, he dejado de pedir directamente por cómo han ido tantas veces las peticiones. Dame el temple de estirar la mano una vez más, por pequeño y de lado que tenga que ser el gesto.","Un gesto pequeño sigue contando como estirar la mano.","Haz hoy una petición de la que te has venido disuadiendo: ayuda, una derivación médica, el tiempo de alguien."],
      ["Le dijo toda la verdad","Marcos 5:30–33","Entonces la mujer, temiendo y temblando, sabiendo lo que en sí había sido hecho, vino y se postró delante de él, y le dijo toda la verdad.","Ella quería llevarse la sanidad y desaparecer. En cambio se le pidió ponerse de pie delante de todos y decirlo todo en voz alta, y esa exposición, que había temido durante doce años, es donde la vergüenza de verdad terminó.","Padre, he venido escondiendo la parte que más me avergüenza. Dame un lugar seguro para decir toda la verdad, y quítame de encima el peso de esconderla.","La parte que escondo es la que más necesita luz.","Dile a una persona de confianza toda la verdad de lo que cargas, no el resumen que sueles dar."],
      ["Hija, ve en paz","Marcos 5:34","Hija, tu fe te ha hecho salva: ve en paz, y queda sana de tu azote.","La llamó hija. Después de doce años de ser un caso, un costo y un diagnóstico, la primera palabra que recibe es una palabra de familia, y ese nombrarla es la parte de la sanidad que nadie más podía darle.","Dios, esta enfermedad se ha llevado mi tiempo y mi dinero, y ha empezado a llevarse mi sentido de quién soy. Pase lo que pase con mi cuerpo, devuélveme mi nombre.","Soy una persona antes que un diagnóstico.","Escribe tres cosas ciertas sobre quién eres que no tengan nada que ver con tu salud. Guárdalas donde las leas en un día malo."]
    ]
  },
  zarephath: {
    name: "La última comida — 1 Reyes 17",
    short: "La última comida",
    weeks: ["HISTORIA DE VALOR · LA ÚLTIMA COMIDA · 1 REYES 17"],
    days: [
      ["Un puñado de harina","1 Reyes 17:12","Solamente un puñado de harina tengo en la tinaja, y un poco de aceite en una botija.","Ella veía el fondo de la tinaja y ya había hecho la cuenta. El miedo financiero rara vez es irracional: suele ser un cálculo correcto llevado hasta una conclusión a la que todavía nadie ha llegado.","Dios, he contado lo que queda y el número no me gusta. Guárdame de vivir el final antes de que llegue, y dame firmeza suficiente para pasar la parte de hoy.","He contado bien y aun así no conozco el final.","Escribe los números reales: lo que hay, lo que se debe, cuándo vence. El miedo hace peores cuentas a oscuras."],
      ["Hazme primero una torta","1 Reyes 17:13","No hayas temor; ve, haz como has dicho.","La petición suena escandalosa, y conviene decir claramente lo que no es: no es un intercambio, no es una técnica para producir dinero y no es razón para regalar lo que tu familia necesita. Es un pequeño acto de confianza justo en el punto donde el miedo dice que cierres la mano.","Señor, la escasez me ha hecho apretarlo todo. Muéstrame una manera honesta y proporcionada de abrir hoy la mano: no con imprudencia, pero de verdad.","El miedo dice cierra la mano; yo puedo abrirla un poco.","Haz una cosa generosa y pequeña que esté de verdad a tu alcance: una comida, una hora, una habilidad que alguien necesita. Pequeña y real, no grande e imprudente."],
      ["La tinaja no escaseó","1 Reyes 17:16","Y la tinaja de la harina no escaseó, ni menguó la botija del aceite.","Lo que recibió nunca fue una reserva. Fue una tinaja que seguía sin vaciarse: suficiente cada vez que acudía a ella, y nunca más que eso, un regalo más difícil de confiar que una suma de una sola vez.","Padre, sigo pidiendo un excedente para dejar de depender de Ti a diario. Enséñame a confiar en una tinaja que se vuelve a llenar en lugar de un montón que tranquiliza.","Lo suficiente, una y otra vez, es una provisión verdadera.","Repasa los últimos doce meses y escribe tres veces en que la tinaja no se vació: el trabajo inesperado, la cuenta que bajó, la ayuda que llegó."],
      ["Muchos días","1 Reyes 17:15","Y comió él, y ella y su casa, muchos días.","No hay escena dramática al final de esta historia: solo muchos días corrientes de una casa comiendo. La provisión que sigue llegando en silencio es fácil de dejar de notar, y notarla es casi todo lo que calma a una mente asustada.","Dios, déjame notar lo que sigue llegando. Antes de contar mañana lo que falta, déjame contar lo que de verdad hubo hoy en la mesa.","La mesa de hoy no estuvo vacía.","Esta noche, nombra en voz alta tres cosas que se te dieron hoy. Hazlo otra vez mañana: la práctica está en la repetición."]
    ]
  },
  jordan: {
    name: "El río — Josué 3–4",
    short: "El río",
    weeks: ["HISTORIA DE VALOR · EL RÍO · JOSUÉ 3–4"],
    days: [
      ["En tiempo de crecida","Josué 3:15","Porque el Jordán suele reverter sobre todos sus bordes todo el tiempo de la siega.","Llegaron al cruce justo en la temporada en que el río venía más alto. El momento parece un error, y vale la pena notar con qué frecuencia lo que se te pide hacer llega cuando las condiciones están peor.","Dios, el momento de esto es pésimo y no dejo de leerlo como señal de que me equivoqué. Dame firmeza para mirar el agua con honestidad y aun así avanzar hacia ella.","Un mal momento no es lo mismo que una puerta cerrada.","Escribe qué hace exactamente que este sea el momento equivocado. Después pregúntate si algo de eso está en tu control."],
      ["Los pies en el agua","Josué 3:13","Las aguas del Jordán se partirán: porque las aguas que vienen de arriba se detendrán en un montón.","El río se partió después de que entraron, no antes. El orden es toda la lección: la evidencia que esperas está del otro lado del paso que te niegas a dar.","Señor, Te he pedido que partas esto antes de dar el paso. Dame el temple de meter un pie mientras aún está hondo, y encuéntrame allí.","El camino se abre después del paso, no antes.","Da el paso que has venido reteniendo hasta sentirte seguro. Hoy, no cuando mejoren las condiciones."],
      ["De pie en medio","Josué 3:17","Estuvieron en seco, firmes en medio del Jordán, hasta que todo el pueblo hubo acabado de pasar el Jordán.","Mientras todos cruzaban, algunos se quedaron quietos en el cauce sosteniendo el peso. No todo papel en un rescate es dramático: parte de él es permanecer en un lugar incómodo el tiempo suficiente para que otros lleguen al otro lado.","Padre, dame paciencia para sostener mi puesto mientras otros pasan. Guárdame de resentir un papel que nadie mira y que todos necesitan.","Sostenerme firme por otros es también una forma de cruzar.","Nombra a la persona que está cruzando gracias a tu firmeza. Haz hoy una cosa que se lo facilite."],
      ["Doce piedras","Josué 4:6–7","Y estas piedras serán por memoria á los hijos de Israel para siempre.","Sacaron piedras del cauce y las apilaron porque sabían que iban a olvidar. La memoria no es automática; el miedo la sobrescribe rápido, y una liberación que no puedes recordar no puede sostenerte la próxima vez.","Dios, he olvidado cosas que ya hiciste. Ayúdame a marcar esta para que la próxima versión asustada de mí tenga algo sólido que mirar.","Construiré algo que pueda señalar después.","Escribe este cruce con detalle simple: la fecha, lo que temías, lo que pasó. Ponlo donde vuelvas a encontrarlo."]
    ]
  },
  torches: {
    name: "Los trescientos — Jueces 6–7",
    short: "Los trescientos",
    weeks: ["HISTORIA DE VALOR · LOS TRESCIENTOS · JUECES 6–7"],
    days: [
      ["El menor en la casa de mi padre","Jueces 6:15","He aquí que mi familia es pobre en Manasés, y yo el menor en la casa de mi padre.","Su primera respuesta fue un currículum de razones por las que él era la persona equivocada. El miedo a no ser suficiente convence precisamente porque sus datos suelen ser exactos: de verdad era el menor de la familia más pequeña.","Dios, todo lo que enumeré sobre por qué esto no debería tocarme a mí es cierto, y aun así no has retirado el encargo. Déjame dejar de audicionar para esto y simplemente empezar.","Ser la persona equivocada en el papel no me ha descalificado.","Escribe tu lista honesta de por qué no eres el indicado. Después haz de todos modos la primera parte pequeña."],
      ["Llamado en el lagar","Jueces 6:11–12","Jehová es contigo, varón esforzado.","Estaba escondido cuando lo llamaron varón esforzado, lo cual era o una broma o la descripción de algo todavía no visible. A menudo se nombra a las personas por aquello en lo que se están convirtiendo y no por donde están paradas.","Señor, se me nombra como algo que no reconozco. Déjame recibirlo en vez de discutirlo, y déjame crecer hacia ello despacio.","Puedo ser llamado algo en lo que aún no me he convertido.","Pregúntale a alguien que te conozca bien qué ve en ti que tú descartas. Anota sus palabras tal cual."],
      ["Son demasiados","Jueces 7:2","El pueblo que está contigo es mucho para que yo dé á los Madianitas en su mano.","Empezó con treinta y dos mil y le dijeron que eran demasiados. El miedo cuenta los recursos y concluye que no se puede; la reducción a trescientos dice que el tamaño nunca fue el punto.","Padre, sigo pidiendo más antes de empezar: más dinero, más tiempo, más certeza, más gente. Muéstrame qué es de verdad suficiente y déjame ir con eso.","He estado esperando más de lo que esto requiere.","Nombra el recurso que insistes en necesitar primero. Planea el siguiente paso de hoy sin él."],
      ["Antorchas dentro de cántaros","Jueces 7:20","Quebrando los cántaros tomaron en las manos izquierdas las teas.","La luz había estado ardiendo todo el tiempo, escondida dentro del barro. No se añadió nada en el momento decisivo: algo se rompió, y lo que se llevaba en silencio por fin se vio.","Dios, he pasado mucho tiempo manteniendo tapadas las partes agrietadas. Si lo que hay dentro es Tuyo, que se vea por la grieta y no a pesar de ella.","Lo que llevo se ve más claro justo donde estoy roto.","Cuéntale a una persona algo difícil que atravesaste, no la versión arreglada. Deja que le sirva."]
    ]
  },
  shipwreck: {
    name: "El naufragio — Hechos 27",
    short: "El naufragio",
    weeks: ["HISTORIA DE VALOR · EL NAUFRAGIO · HECHOS 27"],
    days: [
      ["Ni sol ni estrellas","Hechos 27:20","Y no pareciendo sol ni estrellas por muchos días, y viniendo una tempestad no pequeña.","Catorce días sin cielo significa sin navegación y sin noción del tiempo. Lo más duro de una crisis larga rara vez es la primera noche; es el medio sin rasgos, cuando ya no puedes saber si te estás moviendo.","Dios, he perdido la cuenta de dónde estoy en esto. No veo nada por lo que guiarme. Sostén el rumbo que no alcanzo a ver y guárdame de rendirme a la mitad.","Perder mis referencias no significa que esté perdido.","Marca la fecha de hoy y una frase cierta sobre cómo están las cosas. Estás construyendo el cielo que no puedes ver."],
      ["Yo confío en Dios","Hechos 27:22–25","Os amonesto que tengáis buen ánimo; porque ninguna pérdida habrá de persona de vosotros.","Pablo era un preso en ese barco, sin autoridad sobre nadie, y se volvió la persona más serena de la bodega. En una crisis, la firmeza de una persona es un recurso del que todos los demás toman.","Señor, hazme el sereno de esta sala. No falsamente animado ni fingiendo: solo lo bastante firme para que alguien asustado pueda quedarse cerca de mí.","Mi firmeza es algo que otros pueden tomar prestado.","Dile hoy una cosa cierta y serena a alguien que tenga miedo. Sin optimismo forzado y sin minimizar."],
      ["Tomad alimento","Hechos 27:33–35","Os ruego que comáis por vuestra salud.","Con el barco a punto de partirse, la decisión de liderazgo fue una comida. La crisis te convence de que el cuidado común es un lujo, y es al revés: comer, dormir y descansar son lo que hace posible resistir.","Padre, he venido funcionando con nada y llamándolo urgencia. Devuélveme al cuidado básico. Déjame comer, dormir y seguir a un ritmo que un cuerpo pueda sobrevivir.","El cuidado común no es una distracción de la crisis.","Haz una cosa física que has venido saltándote: una comida de verdad, agua, una hora de sueño, una caminata afuera."],
      ["Sobre tablas rotas","Hechos 27:44","Y así aconteció que todos se salvaron saliendo á tierra.","Nadie llegó en el barco. Llegaron sobre sus restos, agarrados a lo que flotara, y el texto llama a eso salvarse. Se permite que la supervivencia se vea poco digna, y salir en pedazos sigue contando como salir.","Dios, quería salir de esto entero y estoy saliendo en pedazos. Déjame contarlo como rescate y guárdame de despreciar la forma en que llegué hasta aquí.","Llegar sobre los restos sigue siendo llegar.","Nombra una cosa que te sostuvo en esta etapa y de la que te has avergonzado. Dale gracias a Dios por ella."]
    ]
  },
  barley: {
    name: "El campo de cebada — Rut 1–2",
    short: "El campo de cebada",
    weeks: ["HISTORIA DE VALOR · EL CAMPO DE CEBADA · RUT 1–2"],
    days: [
      ["Llena me fui","Rut 1:21","Yo me fuí llena, mas vacía me ha vuelto Jehová.","Noemí volvió a su pueblo con menos de lo que se llevó, y lo dijo en voz alta sin suavizarlo. Empezar de nuevo delante de gente que recuerda tus años mejores es un miedo muy específico.","Dios, estoy de vuelta en un comienzo que no elegí, y estoy cansado de explicarlo. Déjame decir claramente lo que he perdido sin que la pérdida me ponga nombre.","Puedo nombrar lo que perdí sin que se vuelva quién soy.","Di o escribe la frase honesta sobre lo que te ha costado esta etapa. Sin añadirle un lado bueno."],
      ["Donde tú fueres","Rut 1:16","Donde quiera que tú fueres, iré yo; y donde quiera que vivieres, viviré. Tu pueblo será mi pueblo, y tu Dios mi Dios.","Rut se comprometió con alguien justo en el momento en que no tenía sentido práctico: dos viudas, sin ingresos, sin perspectivas. Las decisiones más trascendentes suelen tomarlas personas que no tienen con qué negociar.","Señor, ahora mismo tengo muy poco que ofrecerle a nadie. Déjame de todos modos elegir a alguien, presentarme, comprometerme, y que eso baste.","No tener nada no me descalifica para estar presente.","Haz hoy un compromiso que te cueste algo que en realidad no te sobra: tiempo, presencia, una conversación honesta."],
      ["Fue a dar al campo","Rut 2:3","Espigó en el campo en pos de los segadores.","El texto dice que fue a dar allí por casualidad, que es la broma seca del narrador. Lo que cambió sus circunstancias llegó mientras hacía un trabajo sin brillo que no tenía razón de creer que llevara a ninguna parte.","Padre, no veo a dónde lleva el esfuerzo común de hoy, y me tienta parar. Mantenme trabajando el surco que tengo delante y encárgate Tú de las casualidades.","El trabajo común es donde llega la mayor parte de la provisión.","Haz esa tarea nada llamativa que te has saltado porque parece poco probable que importe."],
      ["Puñados a propósito","Rut 2:16","Antes echaréis á sabiendas de los manojos, y la dejaréis que coja, y no la reprendáis.","Mandó que dejaran caer grano de más donde ella trabajaba, y ordenó a sus hombres no avergonzarla por recogerlo. Ella siguió recogiendo: la ayuda llegó en una forma que le dejó intacta la dignidad.","Dios, hazme de esa clase de persona que ayuda así: en silencio, sin espectáculo, dejándole a la gente su dignidad. Y dame la gracia de recibir ayuda también en esa forma.","La ayuda que protege la dignidad es la mejor de dar y de recibir.","Ayuda hoy a una persona de un modo por el que no tenga que agradecerte en público."]
    ]
  },
};

if (typeof module !== "undefined" && module.exports) module.exports = { esGroups, esTracks };
