// Interface strings for the app shell, in both languages.
//
// The devotional content lives in content.js / content.es.js and the prayer
// composer has its own table in prayers.js (prayerUi). This file is the
// chrome: buttons, headings, aria labels, status messages and the SOS flow.
//
// English is also written into app/index.html as the markup's default, so the
// page reads sensibly before any script runs and the keys document what each
// element is. applyUi() overwrites it when the reader chooses Spanish.
//
// scripts/verify-ui.js fails the build if the two tables do not have exactly
// the same keys, which is how a half-translated release is caught.

const appUi = {
  en: {
    "brand.home": "Stand home",
    "topbar.theme": "Toggle dark mode",
    "topbar.journal": "Open my reflections journal",
    "topbar.prayer": "Open the prayer composer",
    "topbar.library": "Open the 30-day library",
    "progress.aria": "Journey progress",
    "progress.day": "Day {n} of {total}",
    "progress.completeCount": "{done} of {total} complete",
    "progress.streak": " · {n}-day streak",
    "day.share": "Share this day",
    "day.favorite": "Save this day to favorites",
    "day.unfavorite": "Remove this day from favorites",
    "day.number": "DAY {n}",
    "audio.play": "Play daily prayer",
    "audio.pause": "Pause daily prayer",
    "audio.resume": "Resume daily prayer",
    "audio.title": "Guided prayer",
    "audio.length": "About 3 minutes",
    "audio.recorded": "Recorded narration · about 3 minutes",
    "audio.speed": "Narration speed",
    "audio.repeat": "Repeat this prayer until stopped",
    "audio.timer": "Sleep timer",
    "audio.noTimer": "No timer",
    "audio.min": "{n} min",
    "audio.unsupported": "Audio is not supported on this device",
    "section.reflection": "Reflection",
    "section.pray": "PRAY",
    "section.amen": "Amen.",
    "section.declare": "DECLARE",
    "section.practice": "TODAY'S PRACTICE",
    "checkin.kicker": "FEAR CHECK-IN",
    "checkin.question": "Where is your fear right now?",
    "checkin.scale": "1 = calm · 5 = overwhelming",
    "checkin.aria": "Fear level, 1 calm to 5 overwhelming",
    "checkin.noted": "Noted — {n} of 5 today",
    "notes.label": "My reflection",
    "notes.placeholder": "What is God showing me today?",
    "notes.saving": "Saving…",
    "notes.saved": "Saved on this device",
    "notes.failed": "Could not save — storage is unavailable in this browser",
    "day.complete": "Mark day complete",
    "day.completed": "✓ Day complete",
    "day.nav": "Day navigation",
    "day.prev": "← Previous",
    "day.next": "Next →",
    "library.kicker": "YOUR JOURNEYS",
    "library.title": "Choose your path",
    "library.close": "Close library",
    "library.chooseJourney": "Choose a journey",
    "library.finder": "Where are you right now?",
    "library.finderPlaceholder": "Choose what fits…",
    "library.filters": "Filter days",
    "library.all": "All",
    "library.favorites": "Favorites",
    "library.completed": "Completed",
    "library.emptyFavorites": "Tap the heart on any day to save it here.",
    "library.emptyCompleted": "No days completed yet — your journey starts today.",
    "library.cardComplete": " · COMPLETE",
    "library.dayCount": "{done} of {total} days",
    "library.fears": "Start from a fear",
    "library.about": "What Stand does",
    "reminder.label": "Daily reminder",
    "reminder.button": "Add to my calendar",
    "reminder.saved": "Saved for {time} daily — open the downloaded file to add it to your calendar.",
    "reminder.updated": "Updated to {time} daily — open the downloaded file and your calendar will replace the old reminder.",
    "reminder.summary": "Stand — daily prayer",
    "reminder.alarm": "Time to stand",
    "reminder.description": "A few minutes to stand. Open the app: {url}",
    "journal.kicker": "MY REFLECTIONS",
    "journal.title": "Journal",
    "journal.close": "Close journal",
    "journal.empty": "No reflections yet — notes you write on any day will appear here.",
    "journal.download": "Download my reflections (.txt)",
    "journal.backup": "Back up all data (.json)",
    "journal.restore": "Restore from backup",
    "journal.erase": "Erase all data",
    "journal.exportTitle": "STAND — MY REFLECTIONS",
    "journal.exported": "Exported {date}",
    "backup.bad": "That file doesn't look like a Stand backup.",
    "backup.confirm": "Replace the data on this device with this backup?",
    "erase.confirm": "Erase all notes, favorites, and progress from this device? This cannot be undone.",
    "ledger.kicker": "CALM LEDGER",
    "ledger.empty": "Your calm ledger appears here after your first fear check-in.",
    "ledger.drop": "After prayer, your fear drops an average of {avg} points ({n} SOS {sessions}).",
    "ledger.early": "{n} SOS {sessions} recorded — keep standing; the trend takes a few sessions to show.",
    "ledger.week": "Average check-in this week: {avg} of 5 ({n} {checkins}).",
    "ledger.session": "session",
    "ledger.sessions": "sessions",
    "ledger.checkin": "check-in",
    "ledger.checkins": "check-ins",
    "welcome.kicker": "WELCOME",
    "welcome.title": "Thirty days to stand",
    "welcome.body": "Each day pairs Scripture with a short reflection, a guided prayer you can listen to, a declaration to speak, and one small practice.",
    "welcome.point1": "Press ▶ to hear the guided prayer, or read at your own pace.",
    "welcome.point2": "Save favorites with ♡ and keep private notes with ✎ — everything stays on your device.",
    "welcome.point3": "Mark each day complete to track progress and build a daily streak.",
    "welcome.begin": "WHERE WOULD YOU LIKE TO BEGIN?",
    "welcome.core": "The 30-day journey",
    "welcome.coreNote": "The full path from fear to faith",
    "welcome.unknown": "Fear of the unknown",
    "welcome.unknownNote": "A focused five-day track",
    "welcome.night": "Fear at night",
    "welcome.nightNote": "Five days toward rest",
    "welcome.courage": "A courage story",
    "welcome.courageNote": "Four days in one heroic account",
    "install.tip": "Keep Stand one tap away: in Safari, tap",
    "install.share": "Share",
    "install.add": "Add to Home Screen",
    "install.dismiss": "Dismiss install tip",
    "sos.button": "Steady me now",
    "sos.close": "Close",
    "sos.kicker": "STEADY ME",
    "sos.before": "Where is your fear right now?",
    "sos.after": "And now — where is it?",
    "sos.skip": "Skip",
    "sos.breathe": "BREATHE",
    "sos.in": "Breathe in…",
    "sos.hold": "Hold…",
    "sos.out": "Breathe out…",
    "sos.continue": "Continue",
    "sos.breathsLeft": "{n} slow breath to go",
    "sos.breathsLeftPlural": "{n} slow breaths to go",
    "sos.anchor": "ANCHOR",
    "sos.listen": "▶ Hear this prayed",
    "sos.steadier": "I'm steadier",
    "sos.another": "I need another round",
    "sos.wellStood": "WELL STOOD",
    "sos.drop": "Fear {before} → {after}. You stood.",
    "sos.stood": "You stood through it.",
    "sos.closing": "Whatever the next hour holds, this moment was faithfulness. Go gently.",
    "sos.oneMore": "One more round",
    "sos.support": "Fear feels unmanageable? Get support",
    "sos.supportIntro": "If fear feels bigger than you can carry right now, you don't have to carry it alone:",
    "sos.lifeline": "— Suicide & Crisis Lifeline (call or text, 24/7)",
    "sos.textLine": "— Crisis Text Line",
    "sos.emergency": "— if you are in immediate physical danger",
    "sos.textVerb": "Text",
    "sos.textTo": "to",
    "sos.disclaimer": "Stand offers spiritual encouragement. It isn't medical or crisis care, and reaching out for more help is its own act of courage.",
    "share.caption": "“{verse}” — {ref}",
    "share.title": "Day {n}: {title} — Stand",
    "share.cardDay": "D A Y"
  },
  es: {
    "brand.home": "Inicio de Stand",
    "topbar.theme": "Cambiar modo oscuro",
    "topbar.journal": "Abrir mi diario de reflexiones",
    "topbar.prayer": "Abrir el compositor de oraciones",
    "topbar.library": "Abrir la biblioteca de 30 días",
    "progress.aria": "Progreso del camino",
    "progress.day": "Día {n} de {total}",
    "progress.completeCount": "{done} de {total} completados",
    "progress.streak": " · racha de {n} días",
    "day.share": "Compartir este día",
    "day.favorite": "Guardar este día en favoritos",
    "day.unfavorite": "Quitar este día de favoritos",
    "day.number": "DÍA {n}",
    "audio.play": "Reproducir la oración del día",
    "audio.pause": "Pausar la oración del día",
    "audio.resume": "Reanudar la oración del día",
    "audio.title": "Oración guiada",
    "audio.length": "Unos 3 minutos",
    "audio.recorded": "Narración grabada · unos 3 minutos",
    "audio.speed": "Velocidad de la narración",
    "audio.repeat": "Repetir esta oración hasta detenerla",
    "audio.timer": "Temporizador para dormir",
    "audio.noTimer": "Sin temporizador",
    "audio.min": "{n} min",
    "audio.unsupported": "Este dispositivo no admite audio",
    "section.reflection": "Reflexión",
    "section.pray": "ORA",
    "section.amen": "Amén.",
    "section.declare": "DECLARA",
    "section.practice": "PRÁCTICA DE HOY",
    "checkin.kicker": "REGISTRO DEL MIEDO",
    "checkin.question": "¿Dónde está tu miedo ahora mismo?",
    "checkin.scale": "1 = en calma · 5 = abrumador",
    "checkin.aria": "Nivel de miedo, 1 en calma a 5 abrumador",
    "checkin.noted": "Anotado — {n} de 5 hoy",
    "notes.label": "Mi reflexión",
    "notes.placeholder": "¿Qué me está mostrando Dios hoy?",
    "notes.saving": "Guardando…",
    "notes.saved": "Guardado en este dispositivo",
    "notes.failed": "No se pudo guardar — el almacenamiento no está disponible en este navegador",
    "day.complete": "Marcar el día como completado",
    "day.completed": "✓ Día completado",
    "day.nav": "Navegación de días",
    "day.prev": "← Anterior",
    "day.next": "Siguiente →",
    "library.kicker": "TUS CAMINOS",
    "library.title": "Elige tu camino",
    "library.close": "Cerrar la biblioteca",
    "library.chooseJourney": "Elegir un camino",
    "library.finder": "¿Dónde estás ahora mismo?",
    "library.finderPlaceholder": "Elige lo que encaje…",
    "library.filters": "Filtrar días",
    "library.all": "Todos",
    "library.favorites": "Favoritos",
    "library.completed": "Completados",
    "library.emptyFavorites": "Toca el corazón en cualquier día para guardarlo aquí.",
    "library.emptyCompleted": "Aún no has completado ningún día — tu camino empieza hoy.",
    "library.cardComplete": " · COMPLETADO",
    "library.dayCount": "{done} de {total} días",
    "library.fears": "Empieza por un miedo",
    "library.about": "Qué hace Stand",
    "reminder.label": "Recordatorio diario",
    "reminder.button": "Añadir a mi calendario",
    "reminder.saved": "Guardado para las {time} cada día — abre el archivo descargado para añadirlo a tu calendario.",
    "reminder.updated": "Actualizado a las {time} cada día — abre el archivo descargado y tu calendario reemplazará el recordatorio anterior.",
    "reminder.summary": "Stand — oración diaria",
    "reminder.alarm": "Hora de estar firme",
    "reminder.description": "Unos minutos para estar firme. Abre la app: {url}",
    "journal.kicker": "MIS REFLEXIONES",
    "journal.title": "Diario",
    "journal.close": "Cerrar el diario",
    "journal.empty": "Aún no hay reflexiones — las notas que escribas en cualquier día aparecerán aquí.",
    "journal.download": "Descargar mis reflexiones (.txt)",
    "journal.backup": "Respaldar todos los datos (.json)",
    "journal.restore": "Restaurar desde un respaldo",
    "journal.erase": "Borrar todos los datos",
    "journal.exportTitle": "STAND — MIS REFLEXIONES",
    "journal.exported": "Exportado el {date}",
    "backup.bad": "Ese archivo no parece un respaldo de Stand.",
    "backup.confirm": "¿Reemplazar los datos de este dispositivo con este respaldo?",
    "erase.confirm": "¿Borrar todas las notas, favoritos y progreso de este dispositivo? Esto no se puede deshacer.",
    "ledger.kicker": "REGISTRO DE CALMA",
    "ledger.empty": "Tu registro de calma aparece aquí después de tu primer registro del miedo.",
    "ledger.drop": "Después de orar, tu miedo baja en promedio {avg} puntos ({n} {sessions} de calma).",
    "ledger.early": "{n} {sessions} de calma registradas — sigue firme; la tendencia tarda unas cuantas en verse.",
    "ledger.week": "Registro promedio de esta semana: {avg} de 5 ({n} {checkins}).",
    "ledger.session": "sesión",
    "ledger.sessions": "sesiones",
    "ledger.checkin": "registro",
    "ledger.checkins": "registros",
    "welcome.kicker": "BIENVENIDO",
    "welcome.title": "Treinta días para estar firme",
    "welcome.body": "Cada día une la Escritura con una reflexión breve, una oración guiada que puedes escuchar, una declaración para decir en voz alta y una práctica pequeña.",
    "welcome.point1": "Pulsa ▶ para escuchar la oración guiada, o lee a tu propio ritmo.",
    "welcome.point2": "Guarda favoritos con ♡ y escribe notas privadas con ✎ — todo se queda en tu dispositivo.",
    "welcome.point3": "Marca cada día como completado para seguir tu progreso y construir una racha diaria.",
    "welcome.begin": "¿DÓNDE TE GUSTARÍA EMPEZAR?",
    "welcome.core": "El camino de 30 días",
    "welcome.coreNote": "El camino completo del miedo a la fe",
    "welcome.unknown": "Miedo a lo desconocido",
    "welcome.unknownNote": "Un camino enfocado de cinco días",
    "welcome.night": "Miedo de noche",
    "welcome.nightNote": "Cinco días hacia el descanso",
    "welcome.courage": "Una historia de valor",
    "welcome.courageNote": "Cuatro días en un solo relato heroico",
    "install.tip": "Ten Stand a un toque: en Safari, pulsa",
    "install.share": "Compartir",
    "install.add": "Añadir a pantalla de inicio",
    "install.dismiss": "Descartar el aviso de instalación",
    "sos.button": "Calma ahora",
    "sos.close": "Cerrar",
    "sos.kicker": "CALMA",
    "sos.before": "¿Dónde está tu miedo ahora mismo?",
    "sos.after": "¿Y ahora, dónde está?",
    "sos.skip": "Omitir",
    "sos.breathe": "RESPIRA",
    "sos.in": "Inhala…",
    "sos.hold": "Sostén…",
    "sos.out": "Exhala…",
    "sos.continue": "Continuar",
    "sos.breathsLeft": "Queda {n} respiración lenta",
    "sos.breathsLeftPlural": "Quedan {n} respiraciones lentas",
    "sos.anchor": "ANCLA",
    "sos.listen": "▶ Escuchar esta oración",
    "sos.steadier": "Estoy más en calma",
    "sos.another": "Necesito otra ronda",
    "sos.wellStood": "BIEN HECHO",
    "sos.drop": "Miedo {before} → {after}. Te mantuviste firme.",
    "sos.stood": "Te mantuviste firme.",
    "sos.closing": "Traiga lo que traiga la próxima hora, este momento fue fidelidad. Ve con calma.",
    "sos.oneMore": "Una ronda más",
    "sos.support": "¿El miedo se siente inmanejable? Busca apoyo",
    "sos.supportIntro": "Si el miedo se siente más grande de lo que puedes cargar ahora mismo, no tienes que cargarlo solo:",
    "sos.lifeline": "— Línea de Prevención del Suicidio y Crisis (llamada o mensaje, 24/7)",
    "sos.textLine": "— Línea de Crisis por Mensaje",
    "sos.emergency": "— si estás en peligro físico inmediato",
    "sos.textVerb": "Escribe",
    "sos.textTo": "al",
    "sos.disclaimer": "Stand ofrece aliento espiritual. No es atención médica ni de crisis, y pedir más ayuda es en sí mismo un acto de valor.",
    "share.caption": "“{verse}” — {ref}",
    "share.title": "Día {n}: {title} — Stand",
    "share.cardDay": "D Í A"
  }
};

if (typeof module !== "undefined" && module.exports) module.exports = { appUi };
