// Interface strings for the app shell, in both languages.
//
// The devotional content lives in content.js / content.es.js and the prayer
// composer has its own table in prayers.js (prayerUi). This file is the
// chrome: buttons, headings, aria labels, status messages and the SOS flow.
//
// English is also written into app/index.html as the markup's default, so the
// page reads sensibly before any script runs and the keys document what each
// element is. applyUi() overwrites it when the reader chooses Spanish.
//
// scripts/verify-ui.js fails the build if the two tables do not have exactly
// the same keys, which is how a half-translated release is caught.

const appUi = {
  en: {
    "brand.home": "Stand home",
    "topbar.theme": "Toggle dark mode",
    "topbar.journal": "Open my reflections journal",
    "topbar.prayer": "Open the prayer composer",
    "topbar.library": "Open the 30-day library",
    "progress.aria": "Journey progress",
    "progress.day": "Day {n} of {total}",
    "progress.completeCount": "{done} of {total} complete",
    "progress.streak": " · {n}-day streak",
    "day.share": "Share this day",
    "day.favorite": "Save this day to favorites",
    "day.unfavorite": "Remove this day from favorites",
    "day.number": "DAY {n}",
    "audio.play": "Play daily prayer",
    "audio.pause": "Pause daily prayer",
    "audio.resume": "Resume daily prayer",
    "audio.title": "Guided prayer",
    "audio.length": "About 3 minutes",
    "audio.recorded": "Recorded narration · about 3 minutes",
    "audio.speed": "Narration speed",
    "audio.repeat": "Repeat this prayer until stopped",
    "audio.timer": "Sleep timer",
    "audio.noTimer": "No timer",
    "audio.min": "{n} min",
    "audio.unsupported": "Audio is not supported on this device",
    "section.reflection": "Reflection",
    "section.pray": "PRAY",
    "section.amen": "Amen.",
    "section.declare": "DECLARE",
    "section.practice": "TODAY'S PRACTICE",
    "checkin.kicker": "FEAR CHECK-IN",
    "checkin.question": "Where is your fear right now?",
    "checkin.scale": "1 = calm · 5 = overwhelming",
    "checkin.aria": "Fear level, 1 calm to 5 overwhelming",
    "checkin.noted": "Noted — {n} of 5 today",
    "notes.label": "My reflection",
    "notes.placeholder": "What is God showing me today?",
    "notes.saving": "Saving…",
    "notes.saved": "Saved on this device",
    "notes.failed": "Could not save — storage is unavailable in this browser",
    "day.complete": "Mark day complete",
    "day.completed": "✓ Day complete",
    "day.nav": "Day navigation",
    "day.prev": "← Previous",
    "day.next": "Next →",
    "library.kicker": "YOUR JOURNEYS",
    "library.title": "Choose your path",
    "library.close": "Close library",
    "library.chooseJourney": "Choose a journey",
    "library.finder": "Where are you right now?",
    "library.finderPlaceholder": "Choose what fits…",
    "library.filters": "Filter days",
    "library.all": "All",
    "library.favorites": "Favorites",
    "library.completed": "Completed",
    "library.emptyFavorites": "Tap the heart on any day to save it here.",
    "library.emptyCompleted": "No days completed yet — your journey starts today.",
    "library.cardComplete": " · COMPLETE",
    "library.dayCount": "{done} of {total} days",
    "library.fears": "Start from a fear",
    "library.about": "What Stand does",
    "reminder.label": "Daily reminder",
    "reminder.button": "Add to my calendar",
    "reminder.summary": "Stand — daily prayer",
    "reminder.alarm": "Time to stand",
    "reminder.description": "A few minutes to stand. Open the app: {url}",
    "reminder.help": "One reminder for each remaining day of your journey, with that day’s verse, practice and a link straight to it.",
    "reminder.savedPlan": "Saved: {count} reminders, Day {from} to Day {to} of {track}, {time} {cadence} from {start} — open the downloaded file to add them to your calendar.",
    "reminder.savedOne": "Saved: Day {from} of {track}, {time} {start} — open the downloaded file to add it to your calendar.",
    "reminder.updatedPlan": "Updated: {count} reminders, Day {from} to Day {to} of {track}, {time} {cadence} from {start} — open the downloaded file. If your calendar keeps the old series, delete it and import again.",
    "reminder.updatedOne": "Updated: Day {from} of {track}, {time} {start} — open the downloaded file. If your calendar keeps the old reminder, delete it and import again.",
    "reminder.restarted": "You have finished {track}, so this starts again from Day 1.",
    "reminder.today": "today",
    "reminder.tomorrow": "tomorrow",
    "reminder.daySummary": "Stand · Day {n} · {title}",
    "reminder.trackDaySummary": "Stand · {track} · Day {n} · {title}",
    "reminder.dayOf": "Day {n} of {total} · {title}",
    "reminder.practice": "Today’s practice: {text}",
    "reminder.declare": "Declare: {text}",
    "reminder.tipLabel": "Tip: {text}",
    "reminder.openDay": "Open Day {n} in the app: {url}",
    "reminder.readWeb": "Read it on the web: {url}",
    "reminder.alarmDay": "Time to stand — Day {n}: {title}",
    "reminder.tipFirst": "Set aside ten minutes. Read, listen, or both — then mark the day complete.",
    "reminder.tipNight": "Use the sleep timer so the narration stops on its own once you drift off.",
    "reminder.tipHalfway": "You are halfway. Look back at your first notes and see what has shifted.",
    "reminder.tipLast": "This is the last day of this journey. When you finish, choose the next one from the library and add it to your calendar again.",
    "reminder.tipStreak": "Finishing on consecutive days builds a streak. Missing a day does not erase your progress.",
    "reminder.tipAudio": "Press play to hear the day read aloud. Slow the speed if it moves too fast.",
    "reminder.tipNotes": "There is a notes box under each day. A sentence is enough.",
    "reminder.tipSos": "If fear spikes before you get here, tap “Steady me now”. It takes ninety seconds.",
    "reminder.tipCard": "If the verse helped, share it as a card to someone who needs it.",
    "reminder.tipBilingual": "You can read each day in English and Spanish side by side.",
    "reminder.buttonPlan": "Add {count} reminders to my calendar (Day {from}–{to})",
    "reminder.buttonOne": "Add Day {from} to my calendar",
    "reminder.preview": "Preview the first reminder",
    "reminder.shared": "Shared: {count} reminders, Day {from} to Day {to} of {track}, {time} {cadence} from {start}. Choose your calendar app to add them.",
    "reminder.sharedOne": "Shared: Day {from} of {track}, {time} {start}. Choose your calendar app to add it.",
    "reminder.tipHealth": "Prayer walks alongside medical care, never in place of it. Keep your appointments, and bring what the doctor said into the prayer.",
    "reminder.tipMoney": "This journey is not a technique for producing money. Bring the need honestly, and take the practical step that is yours today.",
    "reminder.options": "Options",
    "reminder.fromLabel": "Start with",
    "reminder.fromCurrent": "Where I am",
    "reminder.fromStart": "Day 1",
    "reminder.weekdays": "Weekdays only",
    "reminder.leadLabel": "Alert",
    "reminder.leadNone": "At the time",
    "reminder.leadTen": "10 minutes before",
    "reminder.leadThirty": "30 minutes before",
    "reminder.cadenceDaily": "daily",
    "reminder.cadenceWeekdays": "each weekday",
    "reminder.eveningLabel": "Evening check-in",
    "reminder.eveningHelp": "A second, shorter reminder each evening asking how the practice went.",
    "reminder.eveningMaster": "Stand — evening check-in",
    "reminder.eveningMasterDescription": "How did today’s practice go? Open the app: {url}",
    "reminder.eveningSummary": "Stand · Day {n} · How did it go?",
    "reminder.eveningPractice": "This morning’s practice: {text}",
    "reminder.eveningQuestion": "How did it go? Open the day, mark it complete, and note where your fear is now.",
    "reminder.eveningOpen": "Open Day {n}: {url}",
    "reminder.eveningAlarm": "How did Day {n} go? — {title}",
    "reminder.eveningOn": "An evening check-in at {time} is included.",
    "reminder.eveningCancelled": "The evening check-in series is cancelled. If your calendar keeps it, delete “Stand — evening check-in”.",
    "reminder.subscribeLabel": "Or subscribe",
    "reminder.subscribeHelp": "A calendar feed your calendar app checks on its own, built from the options above and starting on the first day shown. Change the options and subscribe again to move it.",
    "reminder.subscribeLink": "Subscribe in my calendar app",
    "reminder.subscribeCopy": "Copy feed link",
    "reminder.subscribeCopied": "Feed link copied. In Google Calendar choose “From URL”; in Outlook, “Subscribe from web”.",
    "journal.kicker": "MY REFLECTIONS",
    "journal.title": "Journal",
    "journal.close": "Close journal",
    "journal.empty": "No reflections yet — notes you write on any day will appear here.",
    "journal.download": "Download my reflections (.txt)",
    "journal.backup": "Back up all data (.json)",
    "journal.restore": "Restore from backup",
    "journal.erase": "Erase all data",
    "journal.exportTitle": "STAND — MY REFLECTIONS",
    "journal.exported": "Exported {date}",
    "backup.bad": "That file doesn't look like a Stand backup.",
    "backup.confirm": "Replace the data on this device with this backup?",
    "backup.nudge": "Your notes and progress are saved only on this device. A backup keeps them safe if the browser clears its storage.",
    "backup.nudgeIos": "Your notes and progress are saved only on this device, and Safari can clear them after about a week away. Save a backup, or add Stand to your Home Screen to keep them.",
    "backup.nudgeSave": "Save a backup",
    "backup.nudgeLater": "Not now",
    "backup.nudgeSaved": "Backup saved. Keep the file somewhere safe; Restore in the journal brings it back.",
    "erase.confirm": "Erase all notes, favorites, and progress from this device? This cannot be undone.",
    "ledger.kicker": "CALM LEDGER",
    "ledger.empty": "Your calm ledger appears here after your first fear check-in.",
    "ledger.drop": "After prayer, your fear drops an average of {avg} points ({n} calm {sessions}).",
    "ledger.early": "{n} calm {sessions} recorded — keep standing; the trend takes a few sessions to show.",
    "ledger.week": "Average check-in this week: {avg} of 5 ({n} {checkins}).",
    "ledger.session": "session",
    "ledger.sessions": "sessions",
    "ledger.checkin": "check-in",
    "ledger.checkins": "check-ins",
    "welcome.kicker": "WELCOME",
    "welcome.title": "Thirty days to stand",
    "welcome.body": "Each day pairs Scripture with a short reflection, a guided prayer you can listen to, a declaration to speak, and one small practice.",
    "welcome.point1": "Press ▶ to hear the guided prayer, or read at your own pace.",
    "welcome.point2": "Save favorites with ♡ and keep private notes with ✎ — everything stays on your device.",
    "welcome.point3": "Mark each day complete to track progress and build a daily streak.",
    "welcome.begin": "WHERE WOULD YOU LIKE TO BEGIN?",
    "welcome.core": "The 30-day journey",
    "welcome.coreNote": "The full path from fear to faith",
    "welcome.unknown": "Fear of the unknown",
    "welcome.unknownNote": "A focused five-day track",
    "welcome.night": "Fear at night",
    "welcome.nightNote": "Five days toward rest",
    "welcome.courage": "A courage story",
    "welcome.courageNote": "Four days in one heroic account",
    "install.tip": "Keep Stand one tap away: in Safari, tap",
    "install.share": "Share",
    "install.add": "Add to Home Screen",
    "install.dismiss": "Dismiss install tip",
    "sos.button": "Steady me now",
    "sos.close": "Close",
    "sos.kicker": "STEADY ME",
    "sos.before": "Where is your fear right now?",
    "sos.after": "And now — where is it?",
    "sos.skip": "Skip",
    "sos.breathe": "BREATHE",
    "sos.in": "Breathe in…",
    "sos.hold": "Hold…",
    "sos.out": "Breathe out…",
    "sos.continue": "Continue",
    "sos.breathsLeft": "{n} slow breath to go",
    "sos.breathsLeftPlural": "{n} slow breaths to go",
    "sos.anchor": "ANCHOR",
    "sos.listen": "▶ Hear this prayed",
    "sos.steadier": "I'm steadier",
    "sos.another": "I need another round",
    "sos.wellStood": "WELL STOOD",
    "sos.drop": "Fear {before} → {after}. You stood.",
    "sos.stood": "You stood through it.",
    "sos.closing": "Whatever the next hour holds, this moment was faithfulness. Go gently.",
    "sos.oneMore": "One more round",
    "sos.support": "Fear feels unmanageable? Get support",
    "sos.supportIntro": "If fear feels bigger than you can carry right now, you don't have to carry it alone:",
    "sos.lifeline": "— Suicide & Crisis Lifeline (call or text, 24/7)",
    "sos.textLine": "— Crisis Text Line",
    "sos.emergency": "— if you are in immediate physical danger",
    "sos.textVerb": "Text",
    "sos.textTo": "to",
    "sos.textKeyword": "HOME",
    "sos.outsideUs": "Outside the US:",
    "sos.findHelpline": "— free, verified helplines in 175+ countries",
    "sos.disclaimer": "Stand offers spiritual encouragement. It isn't medical or crisis care, and reaching out for more help is its own act of courage.",
    "share.caption": "“{verse}” — {ref}",
    "share.title": "Day {n}: {title} — Stand",
    "share.cardDay": "D A Y",
    "share.kicker": "SHARE",
    "share.heading": "Share this day",
    "share.close": "Close sharing",
    "share.copy": "Copy link",
    "share.copied": "Link copied",
    "share.saveCard": "Save the day's card",
    "share.x": "Share on X",
    "share.facebook": "Share on Facebook",
    "share.whatsapp": "Share on WhatsApp",
    "share.email": "Share by email",
    "share.url": "Page link",
    "share.manual": "Copy the link above.",
    "offline.label": "Keep a week of audio on this device",
    "offline.help": "Saves today’s recording, the next six days and the “Steady me now” sets, about 8 MB, so they play without a connection. Turn it off to free the space.",
    "offline.saving": "Saving {n} of {total}…",
    "offline.saved": "{n} recordings saved on this device · {mb} MB",
    "offline.partial": "{n} of {total} saved; the rest will download the next time you are online.",
    "offline.off": "Nothing is saved on this device."
  },
  es: {
    "brand.home": "Inicio de Stand",
    "topbar.theme": "Cambiar modo oscuro",
    "topbar.journal": "Abrir mi diario de reflexiones",
    "topbar.prayer": "Abrir el compositor de oraciones",
    "topbar.library": "Abrir la biblioteca de 30 días",
    "progress.aria": "Progreso del camino",
    "progress.day": "Día {n} de {total}",
    "progress.completeCount": "{done} de {total} completados",
    "progress.streak": " · racha de {n} días",
    "day.share": "Compartir este día",
    "day.favorite": "Guardar este día en favoritos",
    "day.unfavorite": "Quitar este día de favoritos",
    "day.number": "DÍA {n}",
    "audio.play": "Reproducir la oración del día",
    "audio.pause": "Pausar la oración del día",
    "audio.resume": "Reanudar la oración del día",
    "audio.title": "Oración guiada",
    "audio.length": "Unos 3 minutos",
    "audio.recorded": "Narración grabada · unos 3 minutos",
    "audio.speed": "Velocidad de la narración",
    "audio.repeat": "Repetir esta oración hasta detenerla",
    "audio.timer": "Temporizador para dormir",
    "audio.noTimer": "Sin temporizador",
    "audio.min": "{n} min",
    "audio.unsupported": "Este dispositivo no admite audio",
    "section.reflection": "Reflexión",
    "section.pray": "ORA",
    "section.amen": "Amén.",
    "section.declare": "DECLARA",
    "section.practice": "PRÁCTICA DE HOY",
    "checkin.kicker": "REGISTRO DEL MIEDO",
    "checkin.question": "¿Dónde está tu miedo ahora mismo?",
    "checkin.scale": "1 = en calma · 5 = abrumador",
    "checkin.aria": "Nivel de miedo, 1 en calma a 5 abrumador",
    "checkin.noted": "Anotado — {n} de 5 hoy",
    "notes.label": "Mi reflexión",
    "notes.placeholder": "¿Qué me está mostrando Dios hoy?",
    "notes.saving": "Guardando…",
    "notes.saved": "Guardado en este dispositivo",
    "notes.failed": "No se pudo guardar — el almacenamiento no está disponible en este navegador",
    "day.complete": "Marcar el día como completado",
    "day.completed": "✓ Día completado",
    "day.nav": "Navegación de días",
    "day.prev": "← Anterior",
    "day.next": "Siguiente →",
    "library.kicker": "TUS CAMINOS",
    "library.title": "Elige tu camino",
    "library.close": "Cerrar la biblioteca",
    "library.chooseJourney": "Elegir un camino",
    "library.finder": "¿Dónde estás ahora mismo?",
    "library.finderPlaceholder": "Elige lo que encaje…",
    "library.filters": "Filtrar días",
    "library.all": "Todos",
    "library.favorites": "Favoritos",
    "library.completed": "Completados",
    "library.emptyFavorites": "Toca el corazón en cualquier día para guardarlo aquí.",
    "library.emptyCompleted": "Aún no has completado ningún día — tu camino empieza hoy.",
    "library.cardComplete": " · COMPLETADO",
    "library.dayCount": "{done} de {total} días",
    "library.fears": "Empieza por un miedo",
    "library.about": "Qué hace Stand",
    "reminder.label": "Recordatorio diario",
    "reminder.button": "Añadir a mi calendario",
    "reminder.summary": "Stand — oración diaria",
    "reminder.alarm": "Hora de estar firme",
    "reminder.description": "Unos minutos para estar firme. Abre la app: {url}",
    "reminder.help": "Un recordatorio por cada día que te queda del camino, con el versículo y la práctica de ese día y un enlace directo.",
    "reminder.savedPlan": "Guardado: {count} recordatorios, del día {from} al día {to} de {track}, a las {time} {cadence} desde {start} — abre el archivo descargado para añadirlos a tu calendario.",
    "reminder.savedOne": "Guardado: día {from} de {track}, a las {time} {start} — abre el archivo descargado para añadirlo a tu calendario.",
    "reminder.updatedPlan": "Actualizado: {count} recordatorios, del día {from} al día {to} de {track}, a las {time} {cadence} desde {start} — abre el archivo descargado. Si tu calendario conserva la serie anterior, bórrala e importa de nuevo.",
    "reminder.updatedOne": "Actualizado: día {from} de {track}, a las {time} {start} — abre el archivo descargado. Si tu calendario conserva el recordatorio anterior, bórralo e importa de nuevo.",
    "reminder.restarted": "Has terminado {track}, así que esto empieza de nuevo desde el día 1.",
    "reminder.today": "hoy",
    "reminder.tomorrow": "mañana",
    "reminder.daySummary": "Stand · Día {n} · {title}",
    "reminder.trackDaySummary": "Stand · {track} · Día {n} · {title}",
    "reminder.dayOf": "Día {n} de {total} · {title}",
    "reminder.practice": "Práctica de hoy: {text}",
    "reminder.declare": "Declara: {text}",
    "reminder.tipLabel": "Consejo: {text}",
    "reminder.openDay": "Abre el día {n} en la app: {url}",
    "reminder.readWeb": "Léelo en la web: {url}",
    "reminder.alarmDay": "Hora de estar firme — Día {n}: {title}",
    "reminder.tipFirst": "Reserva diez minutos. Lee, escucha, o ambas cosas — y luego marca el día como completado.",
    "reminder.tipNight": "Usa el temporizador para dormir para que la narración se detenga sola cuando te duermas.",
    "reminder.tipHalfway": "Vas por la mitad. Vuelve a tus primeras notas y mira qué ha cambiado.",
    "reminder.tipLast": "Es el último día de este camino. Cuando termines, elige el siguiente en la biblioteca y añádelo de nuevo a tu calendario.",
    "reminder.tipStreak": "Terminar días seguidos construye una racha. Saltarte un día no borra tu progreso.",
    "reminder.tipAudio": "Pulsa reproducir para escuchar el día en voz alta. Baja la velocidad si va demasiado rápido.",
    "reminder.tipNotes": "Debajo de cada día hay un cuadro de notas. Con una frase basta.",
    "reminder.tipSos": "Si el miedo sube antes de llegar aquí, pulsa «Calma ahora». Son noventa segundos.",
    "reminder.tipCard": "Si el versículo te ayudó, compártelo como tarjeta con alguien que lo necesite.",
    "reminder.tipBilingual": "Puedes leer cada día en inglés y en español, uno junto al otro.",
    "reminder.buttonPlan": "Añadir {count} recordatorios a mi calendario (días {from}–{to})",
    "reminder.buttonOne": "Añadir el día {from} a mi calendario",
    "reminder.preview": "Ver el primer recordatorio",
    "reminder.shared": "Compartido: {count} recordatorios, del día {from} al día {to} de {track}, a las {time} {cadence} desde {start}. Elige tu app de calendario para añadirlos.",
    "reminder.sharedOne": "Compartido: día {from} de {track}, a las {time} {start}. Elige tu app de calendario para añadirlo.",
    "reminder.tipHealth": "La oración acompaña a la atención médica, nunca la sustituye. Mantén tus citas y lleva a la oración lo que dijo el médico.",
    "reminder.tipMoney": "Este camino no es una técnica para producir dinero. Presenta la necesidad con honestidad y da el paso práctico que hoy te corresponde.",
    "reminder.options": "Opciones",
    "reminder.fromLabel": "Empezar por",
    "reminder.fromCurrent": "Donde estoy",
    "reminder.fromStart": "El día 1",
    "reminder.weekdays": "Solo días laborables",
    "reminder.leadLabel": "Aviso",
    "reminder.leadNone": "A la hora",
    "reminder.leadTen": "10 minutos antes",
    "reminder.leadThirty": "30 minutos antes",
    "reminder.cadenceDaily": "cada día",
    "reminder.cadenceWeekdays": "cada día laborable",
    "reminder.eveningLabel": "Revisión de la noche",
    "reminder.eveningHelp": "Un segundo recordatorio, más breve, cada noche, preguntando cómo fue la práctica.",
    "reminder.eveningMaster": "Stand — revisión de la noche",
    "reminder.eveningMasterDescription": "¿Cómo fue la práctica de hoy? Abre la app: {url}",
    "reminder.eveningSummary": "Stand · Día {n} · ¿Cómo fue?",
    "reminder.eveningPractice": "La práctica de esta mañana: {text}",
    "reminder.eveningQuestion": "¿Cómo fue? Abre el día, márcalo como completado y anota dónde está tu miedo ahora.",
    "reminder.eveningOpen": "Abre el día {n}: {url}",
    "reminder.eveningAlarm": "¿Cómo fue el día {n}? — {title}",
    "reminder.eveningOn": "Se incluye una revisión de la noche a las {time}.",
    "reminder.eveningCancelled": "La serie de revisión de la noche queda cancelada. Si tu calendario la conserva, borra «Stand — revisión de la noche».",
    "reminder.subscribeLabel": "O suscríbete",
    "reminder.subscribeHelp": "Un calendario que tu app consulta por sí sola, construido con las opciones de arriba y empezando el primer día mostrado. Cambia las opciones y vuelve a suscribirte para moverlo.",
    "reminder.subscribeLink": "Suscribirme en mi app de calendario",
    "reminder.subscribeCopy": "Copiar enlace del calendario",
    "reminder.subscribeCopied": "Enlace copiado. En Google Calendar elige «Desde URL»; en Outlook, «Suscribirse desde la web».",
    "journal.kicker": "MIS REFLEXIONES",
    "journal.title": "Diario",
    "journal.close": "Cerrar el diario",
    "journal.empty": "Aún no hay reflexiones — las notas que escribas en cualquier día aparecerán aquí.",
    "journal.download": "Descargar mis reflexiones (.txt)",
    "journal.backup": "Respaldar todos los datos (.json)",
    "journal.restore": "Restaurar desde un respaldo",
    "journal.erase": "Borrar todos los datos",
    "journal.exportTitle": "STAND — MIS REFLEXIONES",
    "journal.exported": "Exportado el {date}",
    "backup.bad": "Ese archivo no parece un respaldo de Stand.",
    "backup.confirm": "¿Reemplazar los datos de este dispositivo con este respaldo?",
    "backup.nudge": "Tus notas y tu progreso se guardan solo en este dispositivo. Un respaldo los protege si el navegador borra su almacenamiento.",
    "backup.nudgeIos": "Tus notas y tu progreso se guardan solo en este dispositivo, y Safari puede borrarlos tras una semana sin visitar el sitio. Guarda un respaldo o añade Stand a tu pantalla de inicio para conservarlos.",
    "backup.nudgeSave": "Guardar un respaldo",
    "backup.nudgeLater": "Ahora no",
    "backup.nudgeSaved": "Respaldo guardado. Guarda el archivo en un lugar seguro; Restaurar, en el diario, lo recupera.",
    "erase.confirm": "¿Borrar todas las notas, favoritos y progreso de este dispositivo? Esto no se puede deshacer.",
    "ledger.kicker": "HISTORIAL DE CALMA",
    "ledger.empty": "Tu historial de calma aparece aquí después de tu primer registro del miedo.",
    "ledger.drop": "Después de orar, tu miedo baja en promedio {avg} puntos ({n} {sessions} de calma).",
    "ledger.early": "{n} {sessions} de calma — sigue firme; la tendencia tarda unas cuantas en verse.",
    "ledger.week": "Registro promedio de esta semana: {avg} de 5 ({n} {checkins}).",
    "ledger.session": "sesión",
    "ledger.sessions": "sesiones",
    "ledger.checkin": "registro",
    "ledger.checkins": "registros",
    "welcome.kicker": "BIENVENIDO",
    "welcome.title": "Treinta días para estar firme",
    "welcome.body": "Cada día une la Escritura con una reflexión breve, una oración guiada que puedes escuchar, una declaración para decir en voz alta y una práctica pequeña.",
    "welcome.point1": "Pulsa ▶ para escuchar la oración guiada, o lee a tu propio ritmo.",
    "welcome.point2": "Guarda favoritos con ♡ y escribe notas privadas con ✎ — todo se queda en tu dispositivo.",
    "welcome.point3": "Marca cada día como completado para seguir tu progreso y construir una racha diaria.",
    "welcome.begin": "¿DÓNDE TE GUSTARÍA EMPEZAR?",
    "welcome.core": "El camino de 30 días",
    "welcome.coreNote": "El camino completo del miedo a la fe",
    "welcome.unknown": "Miedo a lo desconocido",
    "welcome.unknownNote": "Un camino enfocado de cinco días",
    "welcome.night": "Miedo de noche",
    "welcome.nightNote": "Cinco días hacia el descanso",
    "welcome.courage": "Una historia de valor",
    "welcome.courageNote": "Cuatro días en un solo relato heroico",
    "install.tip": "Ten Stand a un toque: en Safari, pulsa",
    "install.share": "Compartir",
    "install.add": "Añadir a pantalla de inicio",
    "install.dismiss": "Descartar el aviso de instalación",
    "sos.button": "Calma ahora",
    "sos.close": "Cerrar",
    "sos.kicker": "CALMA",
    "sos.before": "¿Dónde está tu miedo ahora mismo?",
    "sos.after": "¿Y ahora, dónde está?",
    "sos.skip": "Omitir",
    "sos.breathe": "RESPIRA",
    "sos.in": "Inhala…",
    "sos.hold": "Sostén…",
    "sos.out": "Exhala…",
    "sos.continue": "Continuar",
    "sos.breathsLeft": "Queda {n} respiración lenta",
    "sos.breathsLeftPlural": "Quedan {n} respiraciones lentas",
    "sos.anchor": "ANCLA",
    "sos.listen": "▶ Escuchar esta oración",
    "sos.steadier": "Estoy más en calma",
    "sos.another": "Necesito otra ronda",
    "sos.wellStood": "BIEN HECHO",
    "sos.drop": "Miedo {before} → {after}. Te mantuviste firme.",
    "sos.stood": "Te mantuviste firme.",
    "sos.closing": "Traiga lo que traiga la próxima hora, este momento fue fidelidad. Ve con calma.",
    "sos.oneMore": "Una ronda más",
    "sos.support": "¿El miedo se siente inmanejable? Busca apoyo",
    "sos.supportIntro": "Si el miedo se siente más grande de lo que puedes cargar ahora mismo, no tienes que cargarlo solo:",
    "sos.lifeline": "— Línea de Prevención del Suicidio y Crisis: llama y marca 2 para español, o escribe AYUDA al 988 (24/7)",
    "sos.textLine": "— Línea de Crisis por Mensaje, en español",
    "sos.emergency": "— si estás en peligro físico inmediato",
    "sos.textVerb": "Escribe",
    "sos.textTo": "al",
    "sos.textKeyword": "AYUDA",
    "sos.outsideUs": "Fuera de EE. UU.:",
    "sos.findHelpline": "— líneas de ayuda gratuitas y verificadas en más de 175 países",
    "sos.disclaimer": "Stand ofrece acompañamiento espiritual. No es atención médica ni de crisis, y pedir más ayuda es en sí mismo un acto de valor.",
    "share.caption": "“{verse}” — {ref}",
    "share.title": "Día {n}: {title} — Stand",
    "share.cardDay": "D Í A",
    "share.kicker": "COMPARTIR",
    "share.heading": "Compartir este día",
    "share.close": "Cerrar compartir",
    "share.copy": "Copiar enlace",
    "share.copied": "Enlace copiado",
    "share.saveCard": "Guardar la tarjeta del día",
    "share.x": "Compartir en X",
    "share.facebook": "Compartir en Facebook",
    "share.whatsapp": "Compartir en WhatsApp",
    "share.email": "Compartir por correo",
    "share.url": "Enlace de la página",
    "share.manual": "Copia el enlace de arriba.",
    "offline.label": "Guardar una semana de audio en este dispositivo",
    "offline.help": "Guarda la grabación de hoy, los seis días siguientes y las series de “Calma ahora”, unos 8 MB, para escucharlas sin conexión. Desactívalo para liberar el espacio.",
    "offline.saving": "Guardando {n} de {total}…",
    "offline.saved": "{n} grabaciones guardadas en este dispositivo · {mb} MB",
    "offline.partial": "{n} de {total} guardadas; el resto se descargará la próxima vez que tengas conexión.",
    "offline.off": "No hay nada guardado en este dispositivo."
  }
};

if (typeof module !== "undefined" && module.exports) module.exports = { appUi };
