// Shared by the narration build (build-audio.js) and its verifier
// (verify-audio.js): what there is to render, what each item was rendered
// from, where it is filed, and whether the committed manifest still matches.
//
// An item's hash covers its script and every setting that shapes the voice,
// so a content edit, a voice change or a settings change each produce a new
// hash, a new object key and a new URL. Old objects are never overwritten,
// and a CDN can cache every file forever.

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = path.join(__dirname, "..");
const MANIFEST_FILE = path.join(ROOT, "audio-manifest.js");
const VOICES_FILE = path.join(ROOT, "audio-voices.json");

/** Every narration item, from the committed content. */
function loadItems(root = ROOT) {
  const { narrationItems } = require(path.join(root, "narration.js"));
  const { tracks, sosSetsEn } = require(path.join(root, "content.js"));
  const { esTracks, esSos } = require(path.join(root, "content.es.js"));
  const { prayerCorpus } = require(path.join(root, "prayers.js"));
  return narrationItems({ tracks, esTracks, sosSets: sosSetsEn, esSos, prayers: prayerCorpus.traditional });
}

function loadVoices(file = VOICES_FILE) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

/** The voice and delivery settings an item is rendered with. */
function settingsFor(voices, item) {
  const lang = voices[item.lang];
  if (!lang) throw new Error(`audio-voices.json has no voice for ${item.lang}`);
  const kind = lang[item.kind];
  if (!kind) throw new Error(`audio-voices.json has no ${item.kind} settings for ${item.lang}`);
  const settings = {
    voiceId: lang.voiceId, model: lang.model, outputFormat: voices.outputFormat || "mp3_44100_128",
    stability: kind.stability, similarity: kind.similarity, style: kind.style, speed: kind.speed, boost: kind.boost !== false
  };
  // A traditional prayer carries its own pacing (prayers.js, validated by
  // scripts/validate-prayers.js); it wins over the per-kind defaults.
  if (item.kind === "prayer" && item.audio) {
    for (const k of ["stability", "style", "speed"]) if (typeof item.audio[k] === "number") settings[k] = item.audio[k];
  }
  return settings;
}

/** sha256 over the script and the settings, in a fixed key order. */
function itemHash(text, settings) {
  const ordered = {};
  for (const k of Object.keys(settings).sort()) ordered[k] = settings[k];
  return crypto.createHash("sha256").update(JSON.stringify({ text, settings: ordered })).digest("hex");
}

/** "en/day/core/01-stand.7f3a9c2e.mp3", "es/sos/1-salmo-27-1.b91d0c44.mp3",
 * "en/prayer/our-father.3c1e77a0.mp3". */
function keyFor(item, hash, slugify) {
  if (item.kind === "prayer") return `${item.lang}/prayer/${item.slug}.${hash.slice(0, 8)}.mp3`;
  const n = item.index + 1;
  const number = item.kind === "day" ? String(n).padStart(2, "0") : String(n);
  const dir = item.kind === "day" ? `${item.lang}/day/${item.track}` : `${item.lang}/sos`;
  return `${dir}/${number}-${slugify(item.title)}.${hash.slice(0, 8)}.mp3`;
}

/** Every item with its settings, hash and key: the build's work list. */
function planItems({ items, voices, slugify }) {
  return items.map(item => {
    const settings = settingsFor(voices, item);
    const hash = itemHash(item.text, settings);
    return { item, settings, hash, key: keyFor(item, hash, slugify) };
  });
}

/** The committed manifest, read fresh (not from require's cache). */
function readManifest(file = MANIFEST_FILE) {
  delete require.cache[require.resolve(file)];
  return require(file).audioManifest;
}

/** Writes the manifest as the JS module the app loads, atomically. */
function writeManifest(manifest, file = MANIFEST_FILE) {
  const items = {};
  for (const id of Object.keys(manifest.items).sort()) items[id] = manifest.items[id];
  const body = JSON.stringify({ version: manifest.version || 1, enabled: manifest.enabled !== false, base: manifest.base || "", items }, null, 2);
  const src = `// Generated by scripts/build-audio.js. Do not edit by hand: run the build and
// commit the result. Each item is filed under "<lang>/day/<track>/<index>" or
// "<lang>/sos/<index>" or "<lang>/prayer/<id>", with the object key of its recording and the hash of
// the script and voice settings it was rendered from. scripts/verify-audio.js
// fails CI when an item's hash no longer matches the current script, so a
// content edit can never ship stale audio. Days without an entry fall back
// to the device's own narration.
const audioManifest = ${body};

if (typeof module !== "undefined" && module.exports) module.exports = { audioManifest };
`;
  const tmp = `${file}.${process.pid}.tmp`;
  fs.writeFileSync(tmp, src);
  fs.renameSync(tmp, file);
}

/**
 * The manifest against the plan: fresh (hash matches), stale (the script or
 * settings changed since it was rendered), orphan (in the manifest but no
 * longer in the content), missing (in the content, not yet rendered), plus
 * anything malformed.
 */
function manifestReport(manifest, plan) {
  const report = { fresh: [], stale: [], orphan: [], missing: [], problems: [] };
  if (!manifest || typeof manifest !== "object") { report.problems.push("manifest is not an object"); return report; }
  if (typeof manifest.enabled !== "boolean") report.problems.push("enabled must be true or false");
  if (typeof manifest.base !== "string" || (manifest.base && !/^https:\/\/[^/\s]+$/.test(manifest.base))) {
    report.problems.push(`base must be empty or an https origin with no path or trailing slash, not ${JSON.stringify(manifest.base)}`);
  }
  const items = manifest.items && typeof manifest.items === "object" ? manifest.items : (report.problems.push("items must be an object"), {});
  const byId = new Map(plan.map(p => [p.item.id, p]));
  for (const [id, entry] of Object.entries(items)) {
    const p = byId.get(id);
    if (!p) { report.orphan.push(id); continue; }
    if (!entry || typeof entry.key !== "string" || !/^[a-z]{2}\/(day\/[a-z0-9-]+|sos|prayer)\/[a-z0-9-]+\.[0-9a-f]{8}\.mp3$/.test(entry.key)) {
      report.problems.push(`${id}: key is not a recording path: ${JSON.stringify(entry && entry.key)}`); continue;
    }
    if (!/^[0-9a-f]{64}$/.test(entry.hash || "")) { report.problems.push(`${id}: hash is not sha256 hex`); continue; }
    if (entry.hash !== p.hash || entry.key !== p.key) report.stale.push({ id, key: entry.key, expected: p.key });
    else report.fresh.push(id);
  }
  for (const p of plan) if (!(p.item.id in items)) report.missing.push(p.item.id);
  return report;
}

module.exports = { ROOT, MANIFEST_FILE, VOICES_FILE, loadItems, loadVoices, settingsFor, itemHash, keyFor, planItems, readManifest, writeManifest, manifestReport };
